### ISSUE TITLE
关于编码规范的心得体会

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#10]
在阅读《构建之法》第四章以及讨论前后，对项目的编码规范的全新理解以及心得体会。

**Comment by weeway** [comment]
当你是一个孤胆极客时，遵不遵守编程规范似乎不是一件大事。因为所有的代码只要你能看懂，可以编译通过，能在机器跑起来就行。但是，如果是一个团队。这样的方式，就不可行了。在一个团队，同一份代码，经手的人可能就有好几个。每个人如果都按照自己喜好来编写，将会有不同的缩进、不同注释、不同命名方法。对接手的人来说这是很棘手的，他需要去适应不同人的不同风格。光是看懂代码，都需要不少的时间。但是，有了编程规范，大家只要共同遵守一份规约，就能很愉快的合作写代码了。而不用去适应不同人的不同风格，节省时间成本。

**Comment by yootao** [comment]
对于编码规范，其实早有耳闻，但是平常自己写代码的时候却不是很在意。而且自己在写acm题目的时候，一般会喜欢“压行”，比如说同类型变量全部定义在一行，大括号不换行，使用逗号表达式等等。但是现在我们是作为一个团队，写出来的代码不仅仅只有自己一个人看，代码也不是为了AC而生，遵守编码规范将给团队交流带来极大的便利。网上有各式各样的编码规范，该如何编写属于自己团队的编码规范呢？于是我们团队就开了会讨论此问题，最后整理了一份大纲。我相信如果每个人都能够遵守编码规范的话，那么后期的开发效率将大大提高。

**Comment by SANDWICHLiam** [comment]
每个程序猿都有自己敲代码的风格，而且彼此之前的风格大相径庭，如果多人合作完成一个项目的话，彼此之间做好编码规范和代码风格的确定是非常重要的，因为如果不做规范统一，绝大多数的时间会花在理解代码结构上，而不是代码的逻辑功能；在编写PHP编码规范的时候，我发现自己的编码风格不是特别的规范，在每个接口前我会注释该接口所需参数是什么，何种数据类型，调用方式是什么，返回数据的类型是什么，但是在方法中我很少或者基本不会添加代码注视，这样队友在看我的接口代码的时候，就可能需要花时间去理解逻辑，而且一些细节方面我也会不注意，比如｛ 和 ｝另起一行与否，函数方法变量命名要清晰易懂等等，所以我觉得编写编码规范是很重要的，而且对这门语言也会有更加深入的了解。
        尤其是PHP，不仅仅是语言本身的编码规范，还包括了给其他开发者阅读的接口说明规范，采用标准的接口说明是很重要的，因为接口是提供给其他开发者使用的，如果不清晰不准确，很容易造成数据的错误，这样就失去了接口本身应该提供便利的特性了。
        所以，代码的编码规范和风格是我们共同讨论出来的，因此我们每个人对这个编码规范是比较熟悉的，在编程的过程中我也希望自己和队友都能够遵循编码规范，提高开发效率。

**Comment by sleepingshel** [comment]
[编码规范总结_songyufeng.docx](https://github.com/Tutordistribution/Tutor-distribution/files/558752/_songyufeng.docx)

**Comment by Wangtingting007** [comment]
关于编码规范的心得体会

以前做php项目时都是一个人完成所有编码，所以对于编码、命名基本都是我行我素，想怎么来怎么来，现在由于多人合作，编码规范自然是要考虑的。不做不知道，一做吓一跳，自己之前的代码规范性简直为0啊，估计除了自己也没谁看得懂了。组员们一起讨论了许久，最终编码规范总算是确立出来了。通过这次的编码规范作业，相信以后我的代码应该越来越规范!

**Comment by xuowner** [comment]
[编码规范.txt](https://github.com/Tutordistribution/Tutor-distribution/files/559814/default.txt)

**Comment by xuowner** [comment]
由于一直都没注意过编码规范这个问题，都是自己看得懂就好的原则，
通过这次作业了解了编码规范，发现自己以前都是乱来，这样在团队里面
根本是不行的，只有代码规范了之后才能使得整个团队更好的进行编码。
开始学习规范编程，从现在开始做起。

**Comment by CStianya** [comment]
1、对于每一名程序猿，在刚踏入C语言的世界，蹩手蹩脚得输出Hello world时，便已经开始接触到了编码规范。缩进、命名原则、花括号位置等等，这些规范肯定都曾让每个程序猿头疼好久。在自己大一刚接触C语言的时候，并没有考虑过编码规范的问题，但是随着代码写得越来越多，才逐渐深感一份规范得体的代码的重要性。每当别人叫我去帮忙看哪些排版乱七八糟的代码时，无疑是一种地狱般的体验，于是从那时开始，自己便逐渐注意到编码规范的问题，并在自己日常编程中，尽量提升自己的代码规范性和可读性。
2、自己之前也做过几个Android项目，或多或少对项目开发的编程开发有一定的接触和了解。虽说我们团队所负责的是PHP端的项目，但是编程世界万变不离其宗，大致的编码规范都是相同的。而我们小组也有几名组员接触过PHP和前端的编码，因此在开会讨论编码规范时，整体的过程还是比较顺畅的。不过介于我们所制定的编码规范内容太多，便把编码规范文档上传到github上，以免博客内容太长。
