### ISSUE TITLE
第五次冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#100]

**Comment by SANDWICHLiam** [comment]
**【今日进展】**

1. 根据前端的需求修改接口的返回数据
2. 前端完成了Excel导入，并将Excel中的数据插入数据库中，经过测试已经可以使用了
3. 研究Excel导出，已经可以导出成Excel文件

**【存在问题】**

1. 不知道用JS实现页面中table的Excel导出的难度怎么样，反正用PHP导出Excel文件是很简单的，但是！想要导出人性化、好看的格式的Excel文件，真是太复杂了！真是太复杂了！真是太复杂了！当一个导师有多个学生时，需要根据他所拥有的学生数量，去合并一些单元格。。而且PHPExcel对居中、加边框等等样式的操作居然是一个单元格一个单元格的处理，惊呆我了

**【明日安排】**

1. 继续搞excel导出的排版
2. 根据前端的需要修改接口

**【心得体会】**
今天又学到了很多东西，比如Excel的导入导出功能的一些实用经验，搜查了很多的资料和博客，看到了很多国外一些程序猿的也碰到了类似的问题和解决办法，毕竟现在很多地方都会用到Excel导入导出，趁着这个机会，把用PHP实现Excel的导入导出学深入一些，对以后应该是有帮助的，说不定以后回过头来看我现在的处理方式会觉得很愚蠢哈哈

**Comment by xuowner** [comment]
【今日进展】
1.看了些js，aue.js，ajax的内容，还在学习
2.试着敲了选择弹出框的代码
【存在问题】
一点都不熟悉工具，遇到好多bug，可是不会改，沉迷bug，导致效率低下
【明日安排】
继续敲js相关部分的代码
【心得体会】
学了些vue.js的皮毛，看着队友的模板敲，还是出现各种问题，遇到bug的日子就是让人烦躁，没有效率，总是会开始怀疑自己的智商，看着模板也能错，也是无奈了。

**Comment by sleepingshel** [comment]
【今日进展】
修改小细节
写接口
【存在问题】
当初偷了个懒，现在各种细节需要完善
【明日安排】
和许总进行接口对接，给许总的页面赋值
【心得体会】
听说下周三验收，感觉时间又充裕了点，这次beta版本的冲刺应该不会再有全组熬夜等天亮了（这不是个flag
写接口一下觉得轻松很多233333333333

**Comment by weeway** [comment]
**【今日进展】**

1. 对接导师管理界面搜索接口
2. 对接导师管理界面文件上传接口
3. 对接增加导师接口
4. 对接删除导师接口
5. 修改 js 跳转逻辑，让浏览更顺畅

**【存在问题】**

> 修复 bug 时，有一种拆东墙补西墙的感觉。只有在真的，理清思路的情况下才能把 bug 修复好

**【明日安排】**

1. 完成智能匹配界面的修改
2. 对界面进行修改美化

**【心得体会】**
> 我需要冷静一下！为了界面更加流畅，照顾用户体验，取消了点击按钮直接刷新界面的做法。而选择多次调用接口来更新数据据。但是这样做增加了很多的逻辑判断，踩了不少坑！不过这都是值得的！！！

**Comment by yootao** [comment]
【今日进展】
- 今天进展比较缓慢，弄了2个logo，感觉审美已死...

【存在问题】
- 暂无

【明日安排】
- 开始进行前端代码测试的工作，主要是对js代码进行单元测试

【心得体会】

看来设计是条不归路，还是老老实实做程序猿比较靠谱...今天听栋哥说下周三进行beta版本验收，我觉得按照现在的进度应该可以比较顺利的完成，加油！

**Comment by Wangtingting007** [comment]
【今日进展】
1.填报课题：
1）根据当前正在进行导师分配的系别，显示对应设定人数标签
2）对于多重身份的导师，每个系进行导师分配时均可进行学生人数重设，但是设定的人数不能低于已选学生人数
3）对应不同身份更新不同提示信息

2.导师搜索功能
可通过输入导师名称、系别、性别、职称信息进行筛选
输入为空时即可查看原本的专业导师
GIF不小心弄得有点大，上传好几次没成功

3.学生详细信息的接口（接口真的真的好简单啊啊啊）

4.导师最终结果年级下拉框问题修复！！

【存在问题】

无（哈哈哈哈哈哈哈）

【明日安排】

看剧看剧看剧！！！

【心得体会】
今天在宿舍写了将近3个小时吧，感觉很有效率，可能我就是比较适合一个人写代码吧。然后今天还学会了 exp 表达式，写的时候一个不小心就发现之前写的专业导师页面是有问题，代码写错了，导致那些导师并不是根据课题信息判断之后才出来的，今天发现，数据表中的两个字段要想要比较大小不能用之前（'字段一','<','字段二'）而要使用exp 也就是（'字段一   <  字段二'）这样才可以，有没有很神奇！！

**Comment by CStianya** [comment]
![d3005909c11b4eb1b0c073d41381a96c](https://cloud.githubusercontent.com/assets/20432947/21189581/26e80b0e-c25a-11e6-8e06-c2690dda84a5.png)
