### ISSUE TITLE
智能分配算法接口的改进

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#105]

**Comment by SANDWICHLiam** [comment]
**【修改原因】**

1. tc_issues_$grade['grade']表进行了修改，其中修改了学生数的6个字段，导师所带计算机实验班人数、导师所带数学实验班人数、导师所带自然班人数、导师当前计算机实验班人数、导师当前数学实验班人数、导师当前自然班人数
2. alpha版本智能分配接口的参数需要改变
3. 要对计算机实验班和数学实验班进行单独处理

**【修改方法】**

1. 计算机实验班和数学实验班需要单独处理，即计算机/数学实验班的系负责人需要登录自己的帐号对计算机/数学实验班进行智能分配
2. 另外五个系的导师对相应的系的学生进行智能分配
3. 提供两种结果的JSON：导师的角度查看自己的学生和学生的角度查看自己的导师
