### ISSUE TITLE
项目的体系结构设计

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#11]
阐释MVC架构，以及我们的项目如何应用MVC架构。

**Comment by sleepingshel** [comment]
[Uploading 体系结构.docx…]()

**Comment by sleepingshel** [comment]
[Uploading 体系结构.docx…]()

**Comment by sleepingshel** [comment]
[Uploading 体系结构.docx…]()

**Comment by sleepingshel** [comment]
test/体系结构.docx

**Comment by sleepingshel** [comment]
https://github.com/sleepingshel/test/blob/master/体系结构.docx
