### ISSUE TITLE
导师的Excel导入模版

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#110]

**Comment by SANDWICHLiam** [comment]
导入的Excel模版：需要先下载模版，然后根据模版上传对应的Excel文件
导师信息导入模版（导师智能分配系统仅支持.xls格式的Excel，github不能上传.xls，所以上传.xlsx）：
[导入导师信息模版.xlsx](https://github.com/Tutordistribution/Tutor-distribution/files/649067/default.xlsx)
