### ISSUE TITLE
测试——学生和导师信息的Excel文件

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#115]

**Comment by yootao** [comment]
[导师信息.xlsx](https://github.com/Tutordistribution/Tutor-distribution/files/656939/default.xlsx)
[学生信息.xlsx](https://github.com/Tutordistribution/Tutor-distribution/files/656940/default.xlsx)

**Comment by yootao** [comment]
修改版：
[导师信息（改）.xlsx](https://github.com/Tutordistribution/Tutor-distribution/files/659367/default.xlsx)
[学生信息（改）.xlsx](https://github.com/Tutordistribution/Tutor-distribution/files/659368/default.xlsx)
