### ISSUE TITLE
测试问题汇总

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#117]

**Comment by CStianya** [comment]
### 婷婷、玲玲
- 导师个人详细界面职称的显示
- 导师个人详细界面返回按钮样式的统一
- 导师列表的分页显示

### 伟炜
- 时间设置的判断，不能重叠

**Comment by CStianya** [comment]
### 伟炜
- 时间设置的判断，不能重叠

**Comment by CStianya** [comment]
### 婷婷
- 提示信息完善

**Comment by CStianya** [comment]
### 胡总、扬涛
> 服务器上面的可能还没有更新
- 院负责人学生分配情况的分页第一页显示不出来
- 院负责人学生分配情况——点击修改，再点击下一页后又返回到原来的界面

**Comment by Wangtingting007** [comment]
【完成】
提示信息完善
导师个人详细界面——职称的显示
志愿填报界面——导师列表的显示顺序
志愿填报界面——提交志愿后按钮变成修改
课题提交界面——过了课题设置时间段后，界面显示之前设置的信息，但是没有提交按钮

**Comment by Wangtingting007** [comment]
【完成】
全部完成
