### ISSUE TITLE
测试心得

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#118]
- 尽量详尽一点，要放在用户试用报告的博客里面
- 测试过程中发现的问题，以及是如何解决的，之前为什么没有发现这些问题
- 放了三四天假，测试时出现一堆BUG的感想

**Comment by sleepingshel** [comment]
//我写的代码怎么可能会有BUG
感觉系统虽然看上去已经做完了，功能也很完善，可是测试的时候才发现到处都是BUG，还有很多要改的。测试过程基本是做一步改一个BUG，然后继续测继续改。而且程序员之间有的地方没有沟通好，因为每个角色之间都有点或多或少的联系，有的地方没考虑周全就会影响其他功能。

**Comment by xuowner** [comment]
【存在问题】

- 按钮样式不统一
- 选择/拒绝获取学生信息，只能获取第一行学生的信息
- 弹窗的样式是浏览器的样式，风格不统一

【遗漏原因】

- 由于是前端写完代码，后台进行赋值，后台人员在button里面加了a标签导致的问题
- 对js的不熟悉导致只获取第一行的信息
- 这一部分由后台来写，所以遗漏了

【如何改善】

- 把a标签放在button的外面
- 通过学习jquery遍历的内容，还有在队友伟炜的帮助下，get到新知识
- 还未改善完成

【心得体会】

- 测试一步，发现一个bug，沉迷bug，无法自拔，对js的不熟悉，导致花了很多的时间，用了多种方法还是不行，最终还是在队友和外援的帮助下，顺利解决了，感觉理论学习和动手实践还是有很大的差距，理想和现实就是差距巨大。改bug令人烦躁，但是感觉学到了很多东西，懂得了用控制台查看，调试，懂得了JQuery的遍历的方法，还有ajax的使用，终于改完了bug，哈哈哈哈哈哈哈哈哈

**Comment by Wangtingting007** [comment]
【存在问题】

1. 导师个人详细界面——职称的显示
2. 导师列表的分页显示
3. 志愿填报界面——导师列表的显示顺序
4. 志愿填报界面——提交志愿后按钮变成修改
5. 课题提交界面——过了课题设置时间段后，界面显示之前设置的信息，但是没有提交按钮
6. 提示不够完善
7. 弹窗样式不一致

【遗漏原因】

4.5.6.这三个部分主要是因为个人考虑问题，在我眼里算是一个可有可无的功能，但是在别人看来就不一定了，属于人性化设计的问题。
1.这个地方主要是之前数据库中职称和课题填报的课题题目都是title所导致的，后面数据库修改好了，但是我后台赋值的时候忘记了。
2.分页这个问题主要是自己对于thinkphp5分页不够熟悉，写的很差劲，没有发现这个问题主要是之前自己在测试的时候基本就只有4、5个导师，就不会出现前几页丢失问题，昨天测试的时候有30+导师就会导致前几页会丢失。
3.导师列表显示问题，也是因为之前测试数据较少，凑巧成功排序了（真是好尴尬）
7.这个问题的话就是打算测试之前修改一下（原本以为很好改呢。。）

【如何改善】

4.5.6就是按照要求修改就好了，都是比较简单，就不细说了。
1.后台赋值的时候修改title为position。
2.这个问题实际上还没有很理想的对策（能力还不够），目前只是调整了下每页显示的最大数。
3.这个是由于字符编码问题，由于数据库编码是utf8,但是是按照导师名称（即中文，也就是gbk）,order中加入 using gbk即可。
7.这个问题是最最最最难搞得了，由于自己之前比较少用到接口，所以对前端调用接口显示这部分不大理解，昨晚和队友百度到很晚似懂非懂地找了些方法（主要是改写alert这样的）。今天想说自己试着修改一下alert的样式，发现好难啊啊啊啊，最终在立昊大神--前端大神的帮助下总算是把弹窗搞定了！！
【心得体会】

测试一步、BUG一步。。。。。。
What I Can Say??
虽然BUG很多，但感觉自己变得耐心很多，特别是那次改需求之后，基本上是把6个页面重新写了一遍，变得特别耐心，之后遇到BUG就没有那么烦躁了，反而觉得是有东西可以学习了呢~
我真棒！
真棒！
棒！
！

**Comment by weeway** [comment]
**【存在问题】**

1. 本地数据和服务器数据的更新有延迟，导致数据的现实的不一致
2. 分页设置总页数为0时，js 会报类型错误，导致分页栏不能被正常更新
3. 智能匹配界面调用错接口，导致每次刷新结果页面，都重新进行算法分配
4. 按钮的样式不统一

**【遗漏原因】**

1. 在冲刺阶段没有进行详尽的测试，只是测试样例通过就开始写写一个任务
2. 忽略了很多细节的测试，比如，弹窗关闭后是刷新整个页面，还是调用接口刷新局部数据
3. 没有重构代码，代码的条理不够清晰

**【如何改善】**

1. 本地数据和服务器数据的不一致，主要是因为在调用数据的几乎同时，又对服务器数据进行了更新。造成了，本地数据被替换成旧的服务器数据。解决办法为，先更新数据，延迟500ms后再获取服务器数据
2. 抽离公共模块，增加代码的复用度
3. 重构 js ，找到代码上的错误，同时增强代码的可读性 

**【心得体会】**

> 这几天并没有都在休息！虽然没有花很多时间在代码上。但是，总有断断续续地在接后台接口和改善前端界面。中间还对智能匹配界面进行了大修改，这里要感谢一下后台partner，提供了便利的接口！大赞！在界面的修修补补中，发现了自己代码很多不和逻辑的地方。比如界面的刷新、弹窗提示信息、分页的更新、文件重复上传等，都一一改过。重构了代码，觉得一下清爽了很多。解决bug，是既痛苦，又享受的过程。乐在其中！

**Comment by yootao** [comment]
【存在问题】
- 整理的excel表格信息有重复和遗漏之处
- 界面样式不统一

【遗漏原因】
- 给的原始数据就存在错误或重复的问题，比如存在不同的学生学号一样的错误数据，然后整理的时候也没特别注意，直到测试的时候才发现
- 之前没特别注意一些边边角角的界面细节

【如何改善】
- 重新整理数据，然后一行一行检查过去
- 修改样式

【心得体会】
体会了一把手动收集整理学生和导师信息的过程，虽然仅有不到一百条记录，但是还是出现了问题，这也恰恰暴露了传统手工收集信息，手动分配生成结果的弊端，容易导致信息有误。这也是我们开发这个导师互选系统的初衷，降低了流程中由于手工操作而出现错误的可能，方便了用户，同时也提高了工作效率。

**Comment by SANDWICHLiam** [comment]
**【存在问题】**

- 学生个人信息页面、导师个人信息页面、个人信息修改页面被覆盖
- 导师课题信息表的默认设置遗漏
- 接口的小修改很多
- 算法只能固定实现五个志愿数的设置，没有适应可设置的志愿数
- Excel导入时，学生的信息不正确

**【遗漏原因】**

- 系负责人的功能很多，而且功能都较复杂，实现比较麻烦，有些细节在一开始没有全部都考虑周到
- 接口是根据前端的界面实现的，所以需要根据前端的需要修改接口
- 智能分配算法因为有实验班的存在，需要单独处理比较麻烦，有许多地方需要调整没有考虑全面
- 系负责人可以设置志愿数，但是在算法中忘记忘记考虑
- Excel导入没有按照模版规定的格式导入

**【如何改善】**

- 本地有备份，学生个人信息页面、导师个人信息页面、个人信息修改页面从备份中复原
- 在系负责人设置匹配设置的时候，在导师的课题表中自动加入该系所有导师默认的课题信息
- 算法中多传入一个参数，即系负责人设置的志愿数，后台获取学生填报的志愿信息时，根据志愿数获取志愿信息写入文件，并调用算法
- Excel导入后结果不正确是因为导入时没有根据模版导入，导致写入数据库时错误，根据模版的格式导入即正确
- 根据前端的需求修改接口返回信息，改动并不大，主要是返回格式和数据的席位修改

**【心得体会】**

系负责人的功能太多 ，而且实现又比较复杂，所以每天都在敲代码，在测试前写好了所有的接口，但是在测试的时候还是发现了一堆的bug，不过还好这些bug都比较小，只需要稍微做修改就好，beta版本大家对githun的使用都比较熟悉了，所以基本没有产生冲突，而且同步后也都能使用，着实轻松了不少。感谢前端partner，有他在我就可以一直专心的写后台，效率也高了不少，也感谢PM的合理分工，让大家都没有熬夜（我自己熬夜是因为沉迷软工无法自拔，一旦敲代码就停不下来了）。测试中发现了不少的问题，也解决了不少的问题，感觉测试是非常值得去做的。

**Comment by CStianya** [comment]
`031402304 陈燊`

**【存在问题】**

- 测试数据量太大，而且模拟时难以体现出学生和老师的真实选择意愿
- 整个运行流程出现了还几处BUG，基本是边改BUG边进行测试的
- 老师所给的师生信息中有几处是重复的
- 一共七个组员要模拟上百的角色，整个测试过程较为繁琐，而且容易因为粗心而导致填报错误

**【遗漏原因】**

- 老师所给数据信息过少，而且所给信息里面有导师以及学生姓名重复出现的情况
- BUG的出现是由于在开发过程中不同模块之间的沟通不足，导致程序猿的理解出了问题
- 小组里每个人都是第一次接触这么多数据的测试，显得略微有点手忙脚乱，对大量数据的测试方法还不是很科学、规范

**【心得体会】**

	我们项目在测试的前几天就基本已经完成了，这几天来一直都是在为模拟测试进行准备，对系统边边角角的过程进行修补，但尽管如此，在实际模拟测试过程中还是出现了挺多问题，整个测试过程基本都是改一个BUG测试前进一步。其中最大的问题还是在于老师所给的Excel信息里面有出现不同工号或学号的对应同一个名字的信息，以及我们本身对Excel信息的审核不足，才导致了我们在测试到中间阶段时才发现了这个问题。不过其实对最终结果的影响不是很大，只是在填报志愿时和选择学生时会有点误差而已。
	整个测试过程还是挺有价值的，充分验证了我们系统足以经受一百多号人的同时操作。不过这个数据测试量相对还是较少，进一步的测试拟采用整个计算机200多号人的数据进行测试。
