### ISSUE TITLE
“一起买”APP测试

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#119]
### 测试注意点
- 使用体验
- UI鉴赏
- BUG报告
- 改进意见
- 作为用户想要你们加入的功能

**Comment by xuowner** [comment]
【使用体验】
1.修改个人信息，应该在设置里面也有一个选项
2.一直点返回，会回到登录页面，而不是手机桌面，感觉很奇怪
3.评论功能按钮，比较奇怪，感觉不需要也可以，不然换个更好的按钮样式
4.主页下面的图片，没有信息，就一张图不能滚动
5.页面加载太慢
6.我的足迹不知道是什么鬼
【UI鉴赏】
1.颜色很单一，比如搜索按钮也还是白的
2.设置里的三个选项布局很奇怪
【BUG报告】
1.按了发帖，但是没有发帖，按手机的返回键就退到了登录页面
2.搜索按钮点了没反应，就停止运行了
【改进意见】
1.就是登录过之后，在进入app跟从没下载过的一样要重新输入用户名，希望改成可以直接进入主页
2.增加记住密码功能
3.发帖失败要提示为什么失败
4.发帖应该增加*，来显示是必填项
【作为用户想要加入的功能】

**Comment by Wangtingting007** [comment]
【使用体验】
1. 查看帖子时那个三角中间带感叹号的评论按钮感觉很奇葩，建议换个比较显而易见的评论按钮
2. 我的收藏的返回按钮为什么是 back ,其他又是 < ，风格不统一啊
3. 个人信息页面中，为空的地方会显示 null,感觉不大好，用户可能都不知道是什么鬼，最好写个 “空”字或者其他什么的；其次是生日那边如果格式随意填写时，没有给出错误提示，然后查看就会变成 0000-00-00
4. 新建帖子时，部分信息没写时，直接返回发帖失败，原因也不讲一下。。。
5. 发帖什么的都好慢。。。。。。。。
【UI鉴赏】
1. 许多图标不是很统一， 比如 back  、 < 、返回。
2. APP的logo居然是BUY&BUY，然后APP名称是BuyTogether...
【BUG报告】
1. 自己居然可以举报自己，太神奇了！！
2. 打开举报按钮之后无法返回（就是我误点举报按钮，然后不知道怎么返回）
3. 举报信息为空时依然可以举报成功？？！
4. 经常无缘无故就BuyTogether停止运行
【改进意见】
1.解决以上BUG
2.以及UI鉴赏问题
【作为用户想要你们加入的功能】
1. 记住账号密码功能
2. 兼容下小米手机好吗，这么大众的手机呢。

**Comment by CStianya** [comment]
## “一起买”APP测试

### 一、使用体验

- 数据加载实在太慢！切换很不流畅！
- 图标样式没有统一，例如back、<、返回
- Logo的名称是BUT&BUY，然后APP名称却是BuyTogether
- 兼容小米手机！毕竟用户群体很大！
- 对于那些限制格式的输入，应该调用固定的控件，而不能直接输入，而且也没有格式判断和错误提示

### 二、登录、注册、忘记密码界面

- 按钮太靠上，建议放下去一点，然后宽度加宽


- 注册界面和忘记密码界面要加个返回按钮
- 无法进行邮箱注册，获取不到验证码
- 应增加记住帐号密码

### 三、首页界面

- 广告图片高度太高！弄小一点！
- 广告图片应该可以轮播，且点击之后是有反应，比如跳到某个网站链接
- 搜索框太小，很不起眼，应该放在标题栏那里
- 搜素按钮点击没有反应便停止运行
- 进入界面时，搜索框自动聚焦？很不合理
- 点击返回时直接回到登录界面，而不是手机主界面

### 三、个人信息界面

- 个人说明应为多行输入框，而不是单行框
- 性别选项有其他？很人性化！
- 取消和保存的按钮不应该设置为灰色，一看让用户觉得是不能点击的按钮


- 生日格式随意填写，没有给出错误提示，再查看则变成0000-00-00
- 信息为空便显示null（建议为“空”或则其他信息）
- 不能设置用户头像
- 字体太大了！！！小一点！更精炼！

### 四、设置界面

- 版本信息、意见反馈、退出登录的三行要放在正中间
- 点击版本信息和意见反馈没有反应

### 五、帖子详情界面

- 输入框自动聚焦
- 确认按钮应该放在正中间，宽度加宽
- 为什么帖子默认有举报的界面？这不就是在引导用户举报吗？不应该想举报时点击举报按钮，再跳出举报的界面？
- 自己可以举报自己？？？
- 点击举报按钮之后无法返回
- 举报信息为空时可以举报成功
- 帖子的图片占据版面太大，且点击图片后加载不出来


- 查看帖子时那个三角中间带感叹号的评论按钮感觉很奇葩，建议换个比较显而易见的评论按钮
- 返回按钮和删除按钮的颜色没有统一，应该统一为白色

### 六、新建帖子界面

- 新建帖子时，部分信息没写时，直接返回发帖失败，应提示下原因


- 点击发帖，但没有发帖，按返回键就退回了登录界面

- 发帖界面，对于必填信息，可以加 * 号进行标注，如果没有填写实时给出错误提示
- 类别太少了！不应该只有四个！
- 价格后面的灰色“单位”是什么意思？
- 返回时返回到设置界面，应该是界面之间的调用逻辑有问题，没有把一些已经退出的界面在活动栈里销毁

**Comment by CStianya** [comment]
**测试结束，其他人可以不用提交了**
