### ISSUE TITLE
关于“系统设计”作业的总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#12]
总结内容不少于100字！

**Comment by weeway** [comment]
本周任务包括，修改完善需求规格说明书、确定编码规范、数据库设计、系统结构设计和界面设计，每一项都对项目的进展有举足轻重的影响。有了上次的魔鬼一周的经历，这周的稍稍消了一些紧迫感。这次在团队分工中，我负责的部分是编码规范。在平时自己写的小项目中，也有很注意变量的命名，尽量做到见其名知其义，增强可读性。但是，只是知其然。通过这次的作业，我了解到一份编程规范不仅能够增强代码可读性，提高团队协作效率，还能避免一些编程上易犯但隐蔽的错误。还有，能和强大的队友们一起协作，这种感觉真是棒棒哒！

**Comment by yootao** [comment]
这周我的任务主要是修改完善上周提交的需求规格说明书，基本上是对照《GB-T 9385-2008 计算机软件需求规格说明规范》这份国标来修改的。仔细对照国标，发现之前的文档还有许多不完善的地方，存在目录结构不规范，信息冗余等情况，改文档的过程相比写代码是枯燥乏味的，但是如果没有一份详尽的需求规格说明书提供给开发人员的话，那么将会造成后期诸多不必要的麻烦。同时，这周还阅读了《构建之法》第四章中有关编码规范的内容，读后发现有良好的编码规范对于一个团队来说是一件多么重要的事。因此我们开会确定了编码规范，团队编码规范的形成也将对后续开发过程产生有利的帮助。最后，不得不感叹下团队的力量，虽然每周都有高强度的任务要完成，但是大家经常相互交流合作，我相信再难的任务都能啃下来！加油！

**Comment by SANDWICHLiam** [comment]
* 感觉这周组长的分工很合理，每个人都有自己的比较擅长的任务分工，我分配到的任务是 `编写PHP编码规范和代码风格` `修改验收验证标准` `用powerDesigner进行数据库设计和设计E-R图`，终于开始自己比较得心应手的任务了，感觉充满干劲，而且感觉任务压力不会特别大，不像前两周压力那么大
* 在编写PHP编码规范的时候，发现了自己编码有很多不规范的地方，比如在接口代码部分很少或者甚至没有代码注释，`{` 和 `}` 是否另起一行等等许多细节的问题，这些细节的问题看似对编码没有什么影响，但是在团队合作中，编码过程是有队友一起共同完成的，这些细节对于彼此阅读代码就起到至关重要的作用，所以PHP的编码规范和风格可以帮助我们统一代码风格，做到彼此的代码整合后也能够清晰整洁、阅读性强，提高接口的开发效率
* 其次是数据库的设计，在用powerDesigner进行数据库设计的时候，因为共用报课系统的数据库，所以需要考虑到很多的问题，在设计E-R图的时候会思考到许多功能逻辑方面的点，如何实现比较方便且效率高、有没有漏了什么字段等等，但是有一个比较大的问题，比如报课系统他们原先的表没有主键的设置，而我们需要和他们的表进行表关联的时候就非常头疼，修改了许多遍，但是也有好处，就是对系统的功能逻辑变得更加清晰
* 下周就进入编码冲刺阶段了，

**Comment by sleepingshel** [comment]
[作业总结_songyufeng.docx](https://github.com/Tutordistribution/Tutor-distribution/files/558750/_songyufeng.docx)

**Comment by Wangtingting007** [comment]
本次的系统结构主要是由我和另一组员共同完成，感想颇多啊。刚开始动笔的时候我两几乎是懵逼的，愣了许久，依旧憋不出半个字，认真翻阅课本，以及参考网络资料后，仍是不知从何下笔。无奈之下只能请教栋帅，在栋帅的教导下，似懂非懂地噼里啪啦写了一些。心里想着算是写完了，于是便草草交差了。然，在要求严格的组长大大的严格检查下，当然是得重做啦。看得出组长非常认真地看了我们的作业，也看得出来组长应该是 **处女座** 的吧(好挑剔啊)。挑剔是真的很挑剔，但是大多是很有道理的。于是我和队友又重新讨论、查阅资料、查看需求规格书、翻阅课本，花了将近一下午总算完成了(希望不要在退回来😭)。除此以外，感触颇深的就是原形设计了，上次作业是原型的粗糙版本，这次要求做精致的原型，然后真的是好艰辛啊（虽然说并没有画原型），在组长的严要求下，字体大小不行、文本框没对齐不行... ... 原型一改再改，感觉玲玲身体都掏空了。。。。。。就这两个进行得不大顺利吧，软件规格书、编码规范什么的好像还蛮顺利。

**Comment by xuowner** [comment]
这次作业我的主要任务是原型的完善，对于原型设计上面，我和PM有很大的分歧，我认为原型的主要目的是揭示和测试系统的功能与实用性；是通过内容喝结构展示，以及粗略布局，能够像用户说明如何与产品进行交互，应该展示的产品逻辑功能。我花更多的时间在交互上面，PM要求原型的美化，这与我的想法大相径庭让我重新认识了强迫症患者在下周的编码实现中，不得不打起精神才能满足PM的要求。

**Comment by CStianya** [comment]
每一件事情，能全力做好的，就绝不敷衍了事。
沟通，很是重要！
