### ISSUE TITLE
用户指南

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#121]
### 学生用户
- 专业导师、志愿填报、志愿结果模块——玲玲

### 导师用户
- 可选学生、课题提交、志愿结果模块——婷婷

### 系负责人用户
- 学生管理、导师管理、匹配设置模块——伟炜
- 智能分配界面——陈齐民
- 导师和学生的结果查看界面——扬涛

### 院负责人用户
- 设定系负责人、学生分配情况、导师分配情况模块——心颖

### 所有个人信息加修改界面
- 陈齐民

### 文档的整合以及格式的统一
- 陈燊

**Comment by CStianya** [comment]
### 指南注意点
- 截图时浏览器放全屏截图
- 截图上若有需要，则标明“①"、“②”等，并加上适当简略的文字说明
- 在没张截图上附上详细的文字说明
- [Android端报课系统使用手册v1.0 .docx](https://github.com/Tutordistribution/Tutor-distribution/files/665670/Android.v1.0.docx)
- [福州大学大学生创业服务网站使用说明书.docx](https://github.com/Tutordistribution/Tutor-distribution/files/665672/default.docx)

**Comment by Wangtingting007** [comment]
[导师.docx](https://github.com/Tutordistribution/Tutor-distribution/files/666761/default.docx)

**Comment by yootao** [comment]
[系负责人查看结果.docx](https://github.com/Tutordistribution/Tutor-distribution/files/672195/default.docx)

**Comment by xuowner** [comment]
[学生用户指南.docx](https://github.com/Tutordistribution/Tutor-distribution/files/672248/default.docx)

**Comment by weeway** [comment]
[系负责人界面.doc](https://github.com/weeway/Netdisk/raw/master/docs/%E7%B3%BB%E8%B4%9F%E8%B4%A3%E4%BA%BA%E7%95%8C%E9%9D%A2.docx)

**Comment by CStianya** [comment]
胡总：
[院负责人操作手册.docx](https://github.com/Tutordistribution/Tutor-distribution/files/799115/default.docx)
