### ISSUE TITLE
测试的学生信息模板整理

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#122]

**Comment by SANDWICHLiam** [comment]
[数计学院2014级学生实验班名单.xlsx](https://github.com/Tutordistribution/Tutor-distribution/files/795949/2014.xlsx)
[数计学院2014级学生非实验班名单.xlsx](https://github.com/Tutordistribution/Tutor-distribution/files/795951/2014.xlsx)

**Comment by SANDWICHLiam** [comment]
[数计学院2014级学生非实验班名单.xlsx](https://github.com/Tutordistribution/Tutor-distribution/files/801098/2014.xlsx)

**Comment by SANDWICHLiam** [comment]
[数计学院2014级学生实验班名单.xlsx](https://github.com/Tutordistribution/Tutor-distribution/files/801104/2014.xlsx)
