### ISSUE TITLE
软件用途和技术特点

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#123]

**Comment by xuowner** [comment]
1.此系统是用于本科生毕业设计导师选择以及导师选择学生的双向选择。只有双方都选择了对方，才能确定学生的毕业设计导师，以及导师所需要带的毕业设计学生。

2.根据不同角色用户提供不同的功能，以及服务器实时更新不同角色互选的数据，使得用户实时得到结果。毕设师生互选系统可以实现用户的登陆，修改信息以及查看志愿选择的相关信息。

3.程序加载同步服务器实时数据，可以对本地数据进行上传及下载。

4.程序可以进行智能分配，对未选择到导师的学生进行一键分配。

5.编程语言采用PHP，HTML，JAVASCRIPT，C语言，软件开发平台使用Sublime Text 3，系统源程序量为12979行。
