### ISSUE TITLE
服务器部署以及浏览器适配问题的解决

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#124]

**Comment by weeway** [comment]
完成服务器部署
时间控件适配火狐

**Comment by CStianya** [comment]
1、测试服务器地址：http://www.303studio.cn:3030/public/index.php
2、部署服务器地址：http://www.303studio.cn/public/index.php
3、数据库phpMyadmin访问：http://www.303studio.cn:8080
