### ISSUE TITLE
测试时出现的问题

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#129]
- 学生的导师列表无法显示前两页——婷婷
ok
- 系负责人的提示没有实时根据时间坐做出变化——齐民
- 所有分页样式的统一（起码要把当前处在哪一页显示出来）——婷婷、胡总
OK

Re: 时间变化已修改

**Comment by CStianya** [comment]
- 填报志愿时有一个志愿没写，提交后之前已经写的志愿信息都被重置了

**Comment by CStianya** [comment]
- 如果网络延迟，填报志愿时出现两条记录

**Comment by CStianya** [comment]
- 设置系负责人时，如果多名账户在不同页面登陆，出现的冲突问题

**Comment by CStianya** [comment]
- 弹出窗里面的志愿顺序错误

**Comment by CStianya** [comment]
- 老师选择学生时，如果没有学生，提示：对不起，您的手速太慢了，学生都被抢光啦！

**Comment by CStianya** [comment]
- result表里面有sid为0的记录，选择学生时，学生信息没有显示出来时应不能点击确认信息

**Comment by CStianya** [comment]
- 系负责人，导师导出结果时，出现了林锦（没有设置计算机系）

**Comment by CStianya** [comment]
- 学生的志愿结果界面，点击导师名字后，导航栏“志愿结果”左边的图片不见了

**Comment by CStianya** [comment]
- 修改头像时的BUG，一定要改密码才能才能修改头像

**Comment by CStianya** [comment]
- 智能分配里面显示的志愿信息都是第一轮的，没有第二轮的志愿信息

**Comment by CStianya** [comment]
- 智能分配里，手动分配时要突破人数限制——齐民、伟炜

**Comment by CStianya** [comment]
- 院负责人的导出接口——齐民
- 院负责人的导师分配情况的默认显示结果以及分页BUG——胡总

**Comment by SANDWICHLiam** [comment]
1、“系负责人的提示没有实时根据时间坐做出变化”——已修改
2、“设置系负责人时，如果多名账户在不同页面登陆，出现的冲突问题” —— 该问题不存在
3、“系负责人，导师导出结果时，出现了林锦（没有设置计算机系）” —— 导出功能已修改
4、“智能分配里面显示的志愿信息都是第一轮的，没有第二轮的志愿信息” —— 志愿信息已修改，只有一轮志愿信息时，显示一轮的志愿信息，有二轮志愿信息时，显示二轮志愿信息
5、“智能分配里，手动分配时要突破人数限制” —— 系负责人不需要突破限制，院负责人才需要突破限制，院负责人可以突破限制
6、“院负责人的导出接口” —— 院负责人的导出接口已完成
