### ISSUE TITLE
导师列表选择对应导师后 点击返回的设计

### ISSUE THREAD

**Issue by Wasdns** [Tutordistribution/Tutor-distribution#130]
你好：

在选中导师、弹出导师信息之后，点击下方返回按钮，结果是返回第一页而不是刚才的当前页。是否可以改进至停留在刚才的界面？

我的环境：OSX 10.11.5 火狐游览器。

谢谢！

Chen, 2017/3/8

**Comment by CStianya** [comment]
谢谢你的建议，已采纳修改。
