### ISSUE TITLE
选导收尾工作之开发感想

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#132]
- 同一个系统，当由软工作业变成一个真正要上线的项目时，有何感想？
- 为什么在上学期做了那么多的测试，这几星期来还是不断得发现BUG，即使上线运行了也bug不断？
- 从以前都是产品使用者的角度，转变为产品开发、掌控整个系统的人有什么新的体验？
- 其他自己的感想
- **周一晚8点前完成**

大家大概把自己感想说一下，上面几个点，有想法的就多写点，没想法的就大概一下就行。半年来选导系统合作旅程的最后一次心得体会，不是作业，写给自己看。

**Comment by Wangtingting007** [comment]
•	同一个系统，当由软工作业变成一个真正要上线的项目时，有何感想？
小激动小骄傲中夹杂被BUG支配的恐惧！
•	为什么在上学期做了那么多的测试，这几星期来还是不断得发现BUG，即使上线运行了也bug不断？
主要是以下原因：
1）	许多是当初没有考虑的人性化问题，仅仅这个问题就有得改了。
2）	系统时间段多、角色复杂、交互性强，所以做每一个小小的修改时都要多加考虑，稍有不周就会引发另一堆BUG。
3）	系统太过复杂，我们只能从程序员的角度考虑问题，许多细节当时没有考虑清楚（时间段是否连续等），这部分问题就只有系统真正上线问题才会暴露。
4）	上线运行出现的BUG大部分都解决了，还剩一些BUG真的莫名其妙。譬如在本地服务器、我们自己的测试服务器都能好好运行的弹窗以及加载学生信息到了学校服务器就GG了。
•	从以前都是产品使用者的角度，转变为产品开发、掌控整个系统的人有什么新的体验？
担惊受怕，每每软工群有消息，内心都是一颤一颤… … 
•	其他自己的感想
感觉自己好棒啊！（虽然BUG不断）

**Comment by SANDWICHLiam** [comment]
[【陈齐民】系统上线感想.docx](https://github.com/Tutordistribution/Tutor-distribution/files/838385/default.docx)

**Comment by SANDWICHLiam** [comment]
[【陈齐民】系统上线感想.pdf](https://github.com/Tutordistribution/Tutor-distribution/files/838388/default.pdf)

**Comment by orzyt** [comment]
从去年十月份临时改题做毕设选导系统，到今年三月份正式上线投入使用，前后历时近半年真的就这么走过来了！选导系统诞生于栋哥的软件工程实践课，但是其意义对我们来说已经不仅仅是某门课的课程设计作业了，团队每个人都倾尽自己所能让这个系统变得更好、更完善。

虽然当初就被告知该系统有可能在新学期就投入使用，但是当这个时刻真正来临，要从课程作业转变为实际应用的系统，才发现还有许多路要走。系统功能不求多，但是要简单易用，最重要的是要能够稳定运行。因此，上线之前的工作重心主要是在测试方面。拿往年的真实数据过一遍流程，虽然说起来简单，但是做起来却发现问题重重，经常会冒出“这个场景之前怎么没有考虑到”、“怎么每次测试都有新的BUG”等等情况。由于我主要只是写写前端界面和分配算法，调试封装好之后一般没有太大问题，但是心疼后台的同学经常有莫名其妙的BUG要修复...

感觉BUG见多了也会有后遗症，容易把那些不符合直觉（但事后想想又很有道理）的情况当做BUG。比如说零点上线后的几分钟之内，陆续有同学开始填报志愿，但是发现绝大部分同学填的五个志愿是一模一样的！我们守在一线的PM马上联系安卓组排查错误，但最后学弟们则纷纷表示自己就是这样选的，没毛病...

以前自己一直都是作为别人产品的使用者，如今摇身一变成为产品开发人员，让别人来使用自己的产品，这种感觉还是比较特别的。在系统运行的时候，可以开启“上帝视角”监测整个系统的情况，了解每一项数据的变化。但同时更多的还是担心系统能不能平稳地运行、完成好这次选导任务以及出现问题能不能第一时间得到解决等等。

有一个比较遗憾的是在这次选导过程中，智能匹配算法打了一波酱油。主要是因为在第一轮师生互选之后，只剩下三位同学没有分配到导师...（23333机智的学弟学妹们都提前联系好了导师，这也是为什么出现上面提到的五个志愿一模一样的情况，因为这样可以保证只被该导师选中）所以嘛，个位数的数据量也就没算法什么事情了。

选导任务已经结束了，但是 ~系统的维护不会结束~ 团队的友谊不会结束哈哈~

**Comment by weeway** [comment]
在它还是一个作业的时候，心态会比较放松。因为所有的bug都可以悠悠地改，而不涉及到和用户的沟通。一旦变成一个真正要上线的项目时，心里总是会当心系统的稳定性，会不会突然出现一个bug，如果出现了bug要怎么应对，要怎样快速地解决bug。还要时刻做着被用户的吐槽的准备。这真的不是一件容易的事情

上学期的测试，前半部分时间大部分的测试是在本地做的。而后半部分时间的测试主要是在linux上的vps作为服务器做的测试。上线之后的要部署的环境变成了windows server 2000，这让系统运行的不稳定性增加，需要将之前的测试再来过一遍。这再来一遍会忽略不少的细节，往往本地上完好运行的程序，部署到服务器就会出现一些事先没有预知到的事情。比如，在服务器上用notepad打开配置文件修改了配置之后，突然发现所有的用户都无法登录。查来查去最后才发现是notepad是带bomb的。这造成了配置没有办法被正确的加载，连登录功能都不能正常使用。bug的出现总是在意料之外，而意料之外还有修复bug带来的惊喜和欢欣。

**Comment by CStianya** [comment]
[选导系统使用情况与结果报告.docx](https://github.com/Tutordistribution/Tutor-distribution/files/841853/default.docx)
