### ISSUE TITLE
软件需求规格说明书编写—引言以及总体描述

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#2]

**Comment by weeway** [comment]
# 1.引言

## 1.1目的

​	本文档首先给出了毕设导师智能分配系统的总体描述，然后又对功能需求、性能需求和其它非功能性需求进行了详细的描述。通过阅读本文档，客户能够确认产品的确切需求。同时，开发人员能够根据需求进行数据库设计以及整个系统的开发。文档将结合文字描述，流程图、界面原型以及类图等来描述毕设导师智能匹配系统的功能、性能、用户界面、运行环境、外部接口以及针对用户操作给出的各种响应。

该文档详尽说明了这一软件产品的需求和规格，这些规格说明是进行设计的基础，也是编写测试用例和进行系统测试的主要依据。同时，该文档也是用户确定软件功能需求的主要依据

本文档面向多种读者对象：

1. 项目经理：项目经理可以根据该文档了解预期产品的功能，并据此进行系统设计。
2. 设计员：对需求进行分析，并设计出系统，包括数据库的设计。
3. 程序员：配合《设计报告》，了解系统功能，编写《用户手册》。
4. 测试员：根据本文档对软件产品进行功能性测试和非功能性测试。
5. 用户：了解预期产品的功能和性能，并与分析人员一起对整个需求进行讨论和协商。
6. 其他人员：如学校领导、学院领导等可以据此了解产品的功能和性能。



## 1.2范围

​	毕设导师智能匹配系统是本文档要描述的产品。该产品使用对象包括，本学年所有参与选择毕设导师的学生、所有参与选择学生的导师、系负责人以及学院负责人。使用本系统，可以简化传统进行师生匹配的繁琐操作。减少了收集数据、人工核对、人工匹配的可能产生的错误。节省了所有参与人员的宝贵时间。



## 1.3定义、间歇和缩略语

- PM：产品经理
- 本产品（系统）：智能导师匹配系统



## 1.4引用文件

无



## 1.5综述

​	本文档的主要内容共分4部分：总体描述、具体需求、验收验证标准以及其他需求。总体描述部分主要对系统的整体结构进行了大致的介绍；具体需求部分对外部接口需求、功能需求和性能需求进行了详细的描述；验证验收标准部分对系统的验证标准和验证方法进行了详细描述；其他需求定义后期变动的需求，增加和修改的需求。

​	开发小组对用户进行了访谈，通过小组讨论，整理总结出了本文档内容。



# 2.总体描述

## 2.1产品描述

​	毕设导师智能分配系统，将导师分配划分为两个阶段：1、导师学生互选阶段；2、算法匹配和结果微调阶段；本系统将，学生报志愿、系负责人收集整理数据、相关人员进行手工分配、反馈选择结果等繁琐的操作转移到线上。把毕设导师互选的所有流程，传化对本系统的操作。减少了相关人员的工作量，降低了流程中由于手工操作而出现错误的可能。学生的志愿选择、导师分配、数据统计、结果查看及导出等操作均可在上系统完成，提高了毕设导师选择的效率。



## 2.2产品功能

毕设导师智能匹配系统的主要功能：

| 用户   | 功能       | 概述                       |
| ---- | -------- | ------------------------ |
| 学生   | 填报志愿     | 在系统开放填报阶段，学生填选喜欢的导师      |
|      | 查看中选信息   | 学生可以查看中选状态以及所中选的导师信息     |
| 导师   | 报选题和研究方向 | 导师填报研究的课题方向              |
|      | 选择学生     | 导师可在学生列表里选择想要的学生         |
|      | 查看中选信息   | 导师可以查看已经选择的学生以及剩余名额      |
| 系负责人 | 开放报选题    | 系负责人开放系统，供导师填报选题。并设置起止时间 |
|      | 开放志愿填报   | 系负责人开放系统，供学生填报志愿。并设置起止时间 |
|      | 匹配结果微调   | 系负责人对匹配将结果根据实际情况进行修改     |
| 院负责人 | 匹配结果微调   | 院负责人可以对系负责人提交的结果再次进行修改   |
|      | 公布最终结果   | 院负责人将结果导出并公布             |
|      | 设置系负责人   | 员负责人可以添加修改系负责人           |



## 2.3用户特点

| 用户   | 描述                                       |
| ---- | ---------------------------------------- |
| 学生   | 使用本系统的主体用户，使用的主要功能仅有填报导师志愿               |
| 导师   | 使用本系统的主体用户，需要提供选题信息和研究方向，然后选择学生          |
| 系负责人 | 负责本系的导师选择情况，需要掌握本系毕设导师的匹配情况。可以设置本系毕设导师互选的起止时间。对本系的最终匹配结果进行微调 |
| 院负责人 | 在本系统中拥有最高权限。需要掌握整个学院的毕设导师匹配情况，能够设置系负责人。可以全院的匹配结果进行修改。 |



## 2.4约束

| 约束     | 描述                                       |
| ------ | ---------------------------------------- |
| 高级语言需求 | 1、该系统前端将采用 html、javascript 编写。2、服务器端采用 php 编写 |
| 可靠性需求  | 系统的可靠性要求很高                               |
| 并发操作   | 该系统的的用户包含数量较大的学生群体，当同时使用该系统时，可能造成服务不稳定甚至奔溃。后期需要着重考虑并发问题 |



## 2.5假设和依赖关系

假设方面：

- 该系统的用户均能接受并使用该系统
- 开发团队的拥有开该系统的技术储备或者学习能力
- 开发团队能够在规定时间内完成整个系统的开发

依赖方面：

- 毕设导师智能匹配系统的计算需要服务器的支持
- 毕设导师智能匹配系统依赖于学院教务处的学生和导师信息数据库
- 毕设导师智能匹配系统的运行依赖于浏览器

**Comment by weeway** [comment]
word版：[下载地址](https://github.com/weeway/PictureRepository/raw/master/docs/%E5%BC%95%E8%A8%80%E5%8F%8A%E6%80%BB%E4%BD%93%E6%8F%8F%E8%BF%B0.docx)
