### ISSUE TITLE
软件需求规格说明书编写—功能需求

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#3]

**Comment by yootao** [comment]
## 3.2功能需求
### 3.2.1类图

### 3.2.2功能描述（概要）
**3.2.2.1学生**
- 填报志愿
- 修改个人信息
- 查看导师列表
- 查看导师详细信息
- 查看导师的待选学生
- 查看中选导师信息
- 查看中选导师的学生列表
- 查看中选导师的学生信息

**3.2.2.2导师**
- 修改个人信息
- 填报研究的课题方向
- 设置学生数
- 选择学生
- 查看选择自己的学生列表
- 查看选择自己的学生信息
- 查看中选学生列表
- 查看中选学生信息

**3.2.2.3系负责人**
- 批量导入学生信息
- 手动添加学生信息
- 修改学生信息
- 设置志愿个数
- 批量导入导师信息
- 手动添加导师信息
- 修改导师信息
- 设置导师学生数
- 设定各个期限
- 选择自动分配
- 选择强制分配
- 导出分配结果

**3.2.2.4院负责人**
- 修改分配结果
- 导出分配结果
- 设置系负责人

**Comment by yootao** [comment]
### 3.2.3功能描述（详细）

**3.2.3.1学生**
- **填报志愿**：学生可在规定的时间内填报志愿，志愿不允许留空，但不同的志愿可填报相同的导师
- **修改个人信息**：学院、年级、专业、方向、绩点、排名等信息学生无法修改，学生可修改自己的个人简介，包括兴趣方向、特长等
- **查看导师列表**：学生只可查看属于自己方向的导师列表
- **查看导师详细信息**：点击某个导师，可查看该导师的选报课题、所需学生数、导师介绍等
- **查看导师的待选学生**：学生点击某导师，可查看选择该导师的学生列表，但不可查看学生的详细信息
- **查看中选导师信息**：在导师分配结束后，学生可查看中选导师的详细信息
- **查看中选导师的学生列表**：在导师分配结束后，学生可查看中选导师的学生列表
- **查看中选导师的学生信息**：在导师分配结束后，学生可查看中选导师的学生的信息，例如邮箱、电话、QQ等信息，方便同一导师的学生相互之间的联系

**3.2.2导师**
- **修改个人信息**：在报课题和学生人数阶段后，导师不可修改课题和学生数信息，若要修改，需联系系负责人或者学院负责人进行修改，导师可修改自己的研究方向、邮箱、电话等基本个人信息
- **填报研究的课题方向**：导师填报研究的课题方向
- **设置学生数**：设置所需的学生数，原则上不允许为0
- **选择学生**：在学生填报志愿信息后，导师可以选择确定某些学生为自己的学生
- **查看选择自己的学生列表**：导师可查看所有选择自己的学生
- **查看选择自己的学生信息**：导师可查看所有选择自己的学生的个人详细信息
- **查看中选学生列表**：导师可查看自己选择的学生
- **查看中选学生信息**：导师可查看自己选择的学生的个人详细信息

**3.2.3.3系负责人**
- **批量导入学生信息**：利用Excel表批量导入学生的信息，Excel表的内容有标准的格式，特别要说明学生是否为数学/计算机实验班
- **手动添加学生信息**：可单独添加单个学生的信息，特别要说明学生是否为数学/计算机实验班
- **修改学生信息**：可对学生的信息进行增删改查
- **设置志愿个数**：设置学生填报的志愿个数
- **批量导入导师信息**：利用Excel表批量导入导师的信息，Excel表的内容有标准的格式，特别要说明导师是否为数学/计算机实验班的导师
- **手动添加导师信息**：可单独添加单个导师的信息，特别要说明导师是否为数学/计算机实验班的导师
- **修改导师信息**：可对导师的信息进行增删改查，比如调整导师是否为数学/计算机实验班的导师
- **设置导师学生数**：原则上导师在设置所需学生数后不可修改，若需要修改，导师可自行联系系负责人，系负责人修改导师的所需学生数
- **设定各个期限**：1、设定导师报选题和所需学生人数的开始时间与截止时间 2、设定学生填报导师志愿的开始时间与截止时间 3、设定导师选择确认同学为自己学生的开始时间与截止时间
- **选择自动分配**：学生填报完志愿后，导师无需选择，通过算法进行自动分配导师，在自动分配的结果的基础上，系负责人可对未得到分配的学生进行调整，也可调整已得到分配的学生
- **选择强制分配**：导师互选结束后，对于剩下的未被导师选择的学生，系负责人可根据导师的学生人数情况进行手动调整分配
- **导出分配结果**：将导师分配结果以Excel表形式导出，系负责人只能导出该系的导师分配最终结果

**3.2.3.4院负责人**
- **修改分配结果**：院负责人可以修改已确定的导师分配结果，比如存在导师退休、导师临时退任等情况
- **导出分配结果**：将导师分配结果以Excel表形式导出，院负责人可以导出各个系的导师分配最终结果
- **设置系负责人**：院负责人可以设置每个系的系负责人

**Comment by yootao** [comment]
### 3.2.4用户场景

**3.2.4.1典型用户**
- 李同学——选择毕设导师
![](http://images2015.cnblogs.com/blog/1018687/201610/1018687-20161020220739154-1937175185.png)

**Comment by yootao** [comment]
**3.2.4.2背景**
1、典型用户：
- 主要：李同学、张老师、王系主任
- 次要：陈院主任


2、用户的需要/迫切需要解决的问题：
- 李同学：对导师不了解，也不知道有多少学生将和自己选择同一导师
- 张老师：对学生个人情况不了解，不知道如何选择
- 王系主任：手动分发可选导师给学生，学生填报完毕后，人工收集志愿，费时费力，同时导师分配过程复杂且不透明，还要提醒通知每轮的起止时间
- 陈院主任：手动修改分配结果

**Comment by yootao** [comment]
**3.2.4.3场景**

- Part one

占坑待填...

- Part two

占坑待填...

- Part three

占坑待填...

- Part four

占坑待填...

**Comment by yootao** [comment]
### 3.2.1类图
![](http://images2015.cnblogs.com/blog/1018687/201610/1018687-20161020232653638-1001277358.jpg)

**Comment by yootao** [comment]
word版功能需求：[点击下载][1]
[1]:http://files.cnblogs.com/files/orzyt/毕设系统——功能需求.zip
