### ISSUE TITLE
第一天冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#30]

**Comment by xuowner** [comment]
[https://github.com/xuowner/-/blob/master/%E7%AC%AC%E4%B8%80%E5%A4%A9%E5%86%B2%E5%88%BA%E5%86%85%E5%AE%B9.txt](url)

**Comment by xuowner** [comment]
[https://github.com/xuowner/-.git](url)

**Comment by xuowner** [comment]
[第一天冲刺内容.txt](https://github.com/Tutordistribution/Tutor-distribution/files/573319/default.txt)

**Comment by xuowner** [comment]
[Uploading 第一天冲刺内容.txt…]()

**Comment by xuowner** [comment]
今天做了原型的修改，查看了学长的代码，复习了前端，明天开始正式编码，
目标是一天可以做到一页页面的完成，但是由于即将来临的人工智能考试，有点
担心。

**Comment by sleepingshel** [comment]
现在的进度：还在学PHP，学了部分基础知识，预计这两天开始看框架，任务是做院负责人的功能，和杨桃的页面对接

**Comment by Wangtingting007** [comment]
目前进度：TP框架基本该看的看完了，可以开始开发，但是这两天班级有事情，所以只能拖到后天在做了。
项目中的任务主要是负责学生的导师列表/填报志愿/查看结果以及导师的可选学生列表/填写选题/查看最终结果。

**Comment by yootao** [comment]
今天主要是学习前端知识，先对着学长的代码改改看看效果。明天的任务主要还是继续学习前端知识，以及着手修改分配的算法。遇到的困难点主要是前端是从零开始学习的，进度比较慢。

**Comment by SANDWICHLiam** [comment]
今天改了学生个人信息界面、导师个人信息界面、系负责人个人信息界面、院负责人个人信息界面、导师/系负责人/院负责人在登录后还需要选择进入报课系统/导师分配系统的界面，遇到的主要困难是：我初学前端，感觉压力挺大的，碰到许多问题难以下手解决，需要不断去请教前端大神

**Comment by weeway** [comment]
早上软工实践课上，用SoloLearn-CSS客户端温习了css的基础知识，并实现了一些效果。明天的任务，是结合学长的代码，按照分工，现实一部分的界面。
