### ISSUE TITLE
第二天冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#31]

**Comment by sleepingshel** [comment]
昨日进展：学完了PHP的基础知识，开始看起了ThinkPHP5
存在问题：第一次接触PHP的框架，不太熟悉
今日安排：这几天把TP框架看完，争取在校运会期间能开始敲
心得体会：果然世间语言都是相通的，PHP和C相似的地方挺多的，但是PHP自带各种好用的函数，开心的不行

**Comment by Wangtingting007** [comment]
昨日进展：最近事情有点多，昨天没进展
存在问题：要赶紧行动了
今日安排：明天开始写学生，争取明后天将学生/专业导师界面完成，然后好好利用校运会期间的时间
心得体会：虽然最近事情有点多，但是自己还是应该早些行动起来，免得和后面的考试什么的冲撞了

**Comment by weeway** [comment]
昨日进展：完成了“系负责人时间设置界面”初版
存在问题：初次学习css+html+js ，对css属性、dom操作还不熟悉，在写界面的时候需要调试比较长的时间
今日安排：今明两天继续学习css布局，尝试做出响应式网页，提升用户体验
心得体会：css的语法虽然简单，但是要灵活地组合使用各种属性，来实现特定的效果，还是有很大挑战的。

**Comment by SANDWICHLiam** [comment]
昨日进展：完成了四个用户组的个人信息页面的最终修改，修改了css路径产生的无法显示效果的问题
存在问题：因为对前端不熟悉，在页面的布局调整上花了较大的时间
今日安排：完成匹配设置界面的布局，大致完成css样式
心得体会：临近校运会，作为运动员有比赛要参加，还有考试，感觉时间不够用，Alpha版本的时间也越来越近了，感觉压力好大，但是有靠谱牛逼的队友，还是很放心的

**Comment by yootao** [comment]
昨日进展：主要是在改导师分配算法，还有着手进行导师分配情况界面的设计
存在问题：前端不太熟悉，界面设计进度缓慢
今日安排：打算用模拟数据测试下分配算法，然后继续进行页面设计
心得体会：算法改起来还是比较快的，但是除了这个自己也不会什么...过几天又要出去比赛，希望能够尽快先把第一个界面设计出来

**Comment by xuowner** [comment]
昨日进展：下载了photoshop，想要做毕设的logo，把项目的代码看了一遍
存在问题：p图太难，花了太多时间在看懂别人的代码
今日安排：开始着手编程
心得体会：作为一个渣渣，感觉力不从心，但是能做的就是尽力去做
