### ISSUE TITLE
第三天冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#32]

**Comment by sleepingshel** [comment]
昨日进展：看完了ThinkPhp5框架的基础、架构、控制器，正在看数据库
存在问题：看框架的时候没注意，把第二部分一些可以暂时省略的内容当成了基础看，看的云里雾里，挣扎了半天才发现不用看
今日安排：把数据库看了，模型和视图过一遍，其他的有时间就先留给印象，没时间先省略掉，看完后开始着手敲代码
心得体会：学习的时候比较赶，很多知识都是草草过一遍，记得不劳，也不透彻，虽然开始做的时候已经把知识大体上过一遍了，但估计还要反复回去学，还是要边学边做，不过好在有个印象，也稍微了解了框架的结构，日后去学习也知道去哪里学，而且组里还有两个PHP老司机，可以请教

**Comment by xuowner** [comment]
今日进展：完成了学生角色的专业导师列表
存在问题：专业导师列表界面不够完善，bootstrap的框架不熟悉，而且学长的一些css和js也不懂
明日安排：完成导师端的课题提交界面和可选学生界面，以及完善专业导师列表
心得体会：羡慕队友的高效率，某php民不仅php写的超快，连前端页面都写的6的飞起，默默的抱紧大腿，求带飞

**Comment by weeway** [comment]
昨日进展：完善了“系负责人时间界面”，看了 bootstrap 网格系统
存在问题：因为之前看了 css 基础，就直接纯手敲css样式来实现界面，这样太费劲！虽然有听说过bootstrap，但是因为太懒，就没有去看使用方法。有了纯手敲css的体验，决定还是花一些时间看看bootstrap，提高一下效率
今日安排：在大神队友强大输出下，我们的界面基本上都完成了。所以明天继续学习bootstrap，为后面的界面编写做准备
心得体会：磨刀不误砍柴功！多花点时间熟悉前端框架的使用，可以提高编写页面的效率

**Comment by yootao** [comment]
昨日进展：修改了下算法，然后生成了导师和学生的数据测试下分配算法
存在问题：前端进度缓慢...
今日安排：开始着手学习bootstrap，然后把导师分配情况界面的表格部分完成
心得体会：明天就要出发去比赛了，感觉安排的事情又不能如期完成...只想说，各位队友大神们前端求带飞啊！！

**Comment by Wangtingting007** [comment]
昨日进展：本来打算写学生/可选导师列表，但是发现自己还不会分页，就直接先写志愿分配结果，然并没有写完
存在问题：对tp框架的使用不够熟练，很多东西都是看一会写一会。果然看教程还是应该边看边写，边学边练才能扎实。
今日安排：把昨天没写完的志愿分配结果完成，看看分页。
心得体会：虽然都是php框架，也都是MVC思想，但是不得不说差别真不少啊，之前看完的那些教程，好像基本全忘了，边看边写，总算写了点东西出来。

**Comment by SANDWICHLiam** [comment]
今日进展：完成了匹配设置界面，点击可选导师按钮，弹出可选导师的浮窗
存在问题：分配算法已经实现，但是如果要实现的话还需要把算法单独写成库导入到框架中使用，但是目前不知道如何解决
明日安排：完成匹配设置界面的后台功能，包括正常显示未分配到导师的学生列表和可选导师的列表，并且可以实现手动分配，完成分页功能
心得体会：运动会花了好多的时间，写功能的时间好少，最主要的算法实现分配的功能还不知道要如何导入到框架中实现，准备向其他的phper请教一下
