### ISSUE TITLE
第四天冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#47]

**Comment by Wangtingting007** [comment]
今日进展：把昨天没写完的学生/导师分配结果界面写完了，还写了个学生/志愿填报
存在问题：由于分页还没看，所以就还没写学生/导师列表，然后对里面不同学生（是否实验班）的可选导师不同有点疑问，讲的有点乱啊。
明日安排：看分页，把是否实验班导师、是否实验班学生以及之间的关系在搞清楚一点
心得体会：现在突然觉得栋帅说的软件需求规格书要写得清清楚楚、仔仔细细是非常有道理的，不懂该怎么写的时候看看说明书好像就有点懂了，明天加油啦！

**Comment by SANDWICHLiam** [comment]
今日进展：和伟炜讨论时间设置界面的风格和排版，今天校运会，晚上考试，所以没有什么时间实现功能，在研究如何把扬涛的算法导入框架中
存在问题：感觉时间不够啊，要把重点放到后台功能的实现上面了，比如智能分配算法的导入和实现
明日安排：明天和后天校运会都有比赛，所以可能无法把匹配设置界面的后台功能都实现，但是我尽量完成匹配设置界面的后台功能，包括正常显示未分配到导师的学生列表和可选导师的列表，并且可以实现手动分配，完成分页功能
心得体会：这三天校运会时间比较赶，没有什么时间，感觉任务都没办法按时完成，只能校运会结束后加班加点的把没有实现的功能实现

**Comment by sleepingshel** [comment]
今日进展：把婷婷说的要看的TP框架的部分全都过了一遍，结束纯理论学习阶段
存在问题：为什么看完后我的脑子一片空白！一片空白！一片空白！那种感觉自己会了点什么又觉得啥都不记得的状态
今日安排：接下来去看看学长的代码，然后开始敲
心得体会：这是我第一次学习的时候没练习，然后打算直接上手敲项目代码，好方

**Comment by weeway** [comment]
今日进展：中午用 js 写了表单验证功能，晚上到齐民宿舍讨论了一下界面，愉快地聊了会天
存在问题：今天使用 js 实现了对 css 样式的修改，和元素内容的获取和校验。 虽然把效果实现，但是都是边查边用。花了比较多的时间的调试。这都是因为对jquery的熟悉造成的
今日安排：实现“系负责人导师管理界面”的布局
心得体会：今天遇到了不少问题，请教了前端大神，豁然开朗。还有，就是上 stackoverflow 查遇到的问题，得到的答案都很高质，一般的问题都能得到解决。

**Comment by xuowner** [comment]
今日进展：修改了下导师列表里面的选择按钮，完成普通导师的学生列表
存在问题：git pull下来的内容有问题，只能把页面抓出来写，然后对这个有点不熟悉，导致混乱。学生列表页面的分页跑到了底端，以及下拉框的下拉内容显示不出来。
明日安排：解决分页问题，完成课题提交页面
心得体会：果然回家就会跑去玩，虽然我也不觉得在宿舍我会敲代码，要抓紧时间了，明天希望可以努力多做一点界面。
