### ISSUE TITLE
第五天冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#48]

**Comment by xuowner** [comment]
今日进展：完成普通老师的课题提交页面
存在问题：几个固有的css没有办法实现，没能看出整体的样子，这个问题要等回校之后，找队友帮忙解决。
明日安排：完成最终结果页面（导师端和学生端）
心得体会：感觉到bootstrap的强大之处，真的好好用。一个人完成界面好困难，体会到之前结对编程的优势所在。不懂的地方要当面问！不懂的地方要当面问！不懂的地方要当面问！代码有问题也要及时解决，不然就会导致好几个界面都会出现同样的问题。但是这个问题，还是只能等回校之后才能得到队友的帮忙。

**Comment by Wangtingting007** [comment]
今日进展：框架越来越熟练了，今天很迅速地完成了导师下面的可选学生以及最终结果页面。
存在问题：分页还没看，对，我今天还是没看分页。然后就是对项目的理解还存在一些问题，比如提交课题的时间还有实验班不实验班导师问题，反正就是昨天的问题今天还没解决啦，所以就只写了那两个页面。
明日安排：明天可能比较忙啊，所以只暂定明天在分析清楚下项目或者看分页。
心得体会：虽然今天双十一，但还是乖乖地完成了任务先(因为淑女没钱啊，哈哈哈哈哈哈哈)。感觉就是我所做的页面都相对比较简单，无非就是对数据库的增删改查，再加点分页什么的，项目技术上的难点应该是齐名的只能分配算法的引用以及如何将Excel表格导入问题。还有另一个感触就是，虽然感觉做一件不熟悉的事情看似很复杂很难，但是真真正正地动手去写了，事情就会变得相对简单，继续加油吧，淑女!

**Comment by sleepingshel** [comment]
今日进展：看了部分学长的代码，（清空了自己的购物车，填满了自己的购物车，又清空了自己的购物车，沉迷双十一无法自拔
存在问题：差不多知道我要怎么写了，但是框架的结构还不怎么熟悉，不是很懂写到哪。还有就是我也没想到双十一会过得这么疯，嗨过头了，虽然无比清楚自己要吃土但是停不下来，以致于等我交完最后一笔订单才发现今天过完了。。。。。
明日安排：明天着手写代码（实现校运会期间开始写打码的承诺）明天晚上会回福大，打算骚扰下婷婷，先肛一些功能出来
心得体会：可能没时间仔细看完学长的代码了，但是就我看的这部分而言感觉思路和J2EE里面用SSH框架有点类似，如果我的想法没错的话接下去的部分应该不用看了，就直接写。困难的地方就在于对语法和TP框架自带函数的不熟悉还有对框架目录结构的不熟悉，但是婷婷熟悉熟悉了嘛

**Comment by SANDWICHLiam** [comment]
今日进展：完成未分配导师的学生列表显示
存在问题：点击分配导师按钮，会弹出可选导师的列表，但是在页面实现上是用一个html，只是通过js和css控制显示两个叠层的div，在后台实现上需要点技巧
明日安排：把分页功能实现，然后把时间设置界面的后台实现
心得体会：校运会重头戏才刚来，清空了购物车，但是还有比赛，恨不得每天能多个几个小时，难点还是在怎么运用扬涛写的智能分配算法，到现在还是没有什么思路，不知道要怎么处理

**Comment by weeway** [comment]
今日进展：看了 git 的版本回退和分支操作， 把代码更新部署到腾讯云上
存在问题：今天没敲代码，懒懒地过掉一天。太有罪恶感了！
明日安排：我负责的界面基本上都完成了，这几天看看能不能帮上队友的忙。继续学习 js，打算现实一个ajax 的小demo
心得体会：时间过得好快！还没来得及剁手，双十一就过去了
