### ISSUE TITLE
Bug报告

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#50]

**Comment by sleepingshel** [comment]
/*弱智BUG反馈*/
BUG：
很多都是因为不熟悉php/不熟悉ThinkPhp5引起的，有的真的太low了，就不写了
1.学生结果查询和学生修改用了同一个方法，结果跳转一直出错
	解决：用了隐藏表单传递信息，根据不同的值来判断应该怎么跳转
2.用原生的sql语句查询，后面加上paginate()方法报错
	解决：query()返回的是数组，不可以用paginate(),改成链式查询就好了
3.查询的时候用{}，有个工号带字母的老师引起BUG
	解决：改用占位符
