### ISSUE TITLE
第八次冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#52]

**Comment by xuowner** [comment]
今日进展：修改了之前写的那些页面，使页面看起来更美观了一些，前端内容应该是完成了吧？？？？
存在问题：修改bug能力太菜，使用的bootstrap里面的css，很多都是强制转换
明日安排：准备测试计划
心得体会：一个人敲代码的时候，感觉任务都要做完了，但是整组一起敲代码的时候，才发现原来小问题超级多，都要一起改bug，一起头疼，一起蓝瘦，一起加油，更有干劲！

**Comment by sleepingshel** [comment]
今日进展：把所有页面的分页和赋值做掉了，各种跳转做掉了，蜜汁消失了几个方法，补上了，修改了一些乱七八糟的细节
存在问题：动态刷新的赋值好难做啊，动态刷新的接口对接根本就不会啊，谁能教教我要干什么(╯°Д°)╯︵┴┴
明日安排：争取把接口对接写完，但是心里没什么底。。。。。
心得体会：一堆人一起丸比一个人丸感觉好多了，效率也快多了，下次继续开活动室呗。动态刷新好难啊，各种意义上的难(╯°Д°)╯︵┴┴

**Comment by sleepingshel** [comment]
今日进展：把所有页面的分页和赋值做掉了，各种跳转做掉了，蜜汁消失了几个方法，补上了，修改了一些乱七八糟的细节
存在问题：动态刷新的赋值好难做啊，动态刷新的接口对接根本就不会啊，谁能教教我要干什么(╯°Д°)╯︵┴┴
明日安排：争取把接口对接写完，但是心里没什么底。。。。。
心得体会：一堆人一起丸比一个人丸感觉好多了，效率也快多了，下次继续开活动室呗。动态刷新好难啊，各种意义上的难(╯°Д°)╯︵┴┴

**Comment by sleepingshel** [comment]
今日进展：把所有页面的分页和赋值做掉了，各种跳转做掉了，蜜汁消失了几个方法，补上了，修改了一些乱七八糟的细节
存在问题：动态刷新的赋值好难做啊，动态刷新的接口对接根本就不会啊，谁能教教我要干什么(╯°Д°)╯︵┴┴
明日安排：争取把接口对接写完，但是心里没什么底。。。。。
心得体会：一堆人一起丸比一个人丸感觉好多了，效率也快多了，下次继续开活动室呗。动态刷新好难啊，各种意义上的难(╯°Д°)╯︵┴┴

**Comment by sleepingshel** [comment]
今日进展：把所有页面的分页和赋值做掉了，各种跳转做掉了，蜜汁消失了几个方法，补上了，修改了一些乱七八糟的细节
存在问题：动态刷新的赋值好难做啊，动态刷新的接口对接根本就不会啊，谁能教教我要干什么(╯°Д°)╯︵┴┴
明日安排：争取把接口对接写完，但是心里没什么底。。。。。
心得体会：一堆人一起丸比一个人丸感觉好多了，效率也快多了，下次继续开活动室呗。动态刷新好难啊，各种意义上的难(╯°Д°)╯︵┴┴

**Comment by sleepingshel** [comment]
今日进展：把所有页面的分页和赋值做掉了，各种跳转做掉了，蜜汁消失了几个方法，补上了，修改了一些乱七八糟的细节
存在问题：动态刷新的赋值好难做啊，动态刷新的接口对接根本就不会啊，谁能教教我要干什么(╯°Д°)╯︵┴┴
明日安排：争取把接口对接写完，但是心里没什么底。。。。。
心得体会：一堆人一起丸比一个人丸感觉好多了，效率也快多了，下次继续开活动室呗。动态刷新好难啊，各种意义上的难(╯°Д°)╯︵┴┴

**Comment by Wangtingting007** [comment]
今日进展：把所有页面的分页和赋值做掉了，然后发现，有个地方的业务逻辑没写好，就是每次到时选择学生的时候，没有判断到时当前学生个数
存在问题：如上所述
明日安排：把逻辑完善
心得体会：一群人一起写代码真的是很棒的体验。

**Comment by weeway** [comment]
今日进展：院负责人修改匹配结果的前端界面完成。用 js 写了获取未匹配学生的局部刷新
存在问题：原本是想，把大部分界面都做局部刷新。但是给 html 元素替换数据的时候，发现元素相对位置的逻辑比较难处理，出了一个暂时没法解决的 bug。于是，出 bug 的部分就暂时不做局部刷新~~ 曲线救国 : ) ~~~
明日安排：看测试计划，找一个前端测试工具
心得体会：再一次见到凌晨两点的福大，还是和队友一起。虽然在猝死的道路上越走越远，可是一起敲代码的感觉真的是很棒啊！

**Comment by CStianya** [comment]
从晚上八点到凌晨两点(本来还可以更晚的，但考虑到明早还有课)，四个多小时的共同奋战，原来敲代码也可以这么嗨。一群人在一起敲代码，有问题旁边立马有组员帮忙解答，互相帮助互相学习，感受到了团队的力量是何其之大。一个晚上的时间，明显得感觉到组员完成任务的进度比以前快了好多好多，从燃尽图和任务进展明显可以看出任务完成的粒度比之前多了不少。随着截止期限的迫近，隐藏在每个人身体内的代码小宇宙终于爆发了出来！
而今天，我们也终于等到了组里的IQ担当——杨涛大神回归，不过由于杨涛离开比较久，对组里进度的对接有点难，考虑到杨涛大神出色的文档撰写能力，我便让他负责部分博客内容的撰写。
众人拾柴火焰高，未来几天我们会继续相约活动室，共同见证福大的凌晨，见证一个项目从零到一的过程！

**Comment by sleepingshel** [comment]
明明是组长想睡觉才回去的

**Comment by SANDWICHLiam** [comment]
今日进展：完成了除了算法之外的其他自己负责的部分
存在问题：可选导师的按钮样式要做稍微的调整，然后算法还是没有成功的调用，心好累啊，仍然在各种搜索
明日安排：有一些小细节比如css样式稍作微调，继续研究算法如何调用
心得体会：今晚整个团队一起码代码，感觉氛围非常好而且沟通问题很方便，解决问题也很方便，有bug可以一起讨论一起解决，还从伟炜那里学了一些js的知识，接下来可以多几次一起码代码，效率挺高的感觉

**Comment by yootao** [comment]
今日进展：今天才刚长途跋涉回到学校，晚上就又要开站立式会议，然后大家就在活动室里一起解决问题，我则在帮组长写文档，自学js等
存在问题：任务比较轻松，还木有问题
明日安排：继续学习js，然后修改自己负责的界面等
心得体会：第一次大家一起在活动室敲代码，感觉真的很不一样，一个人可能会松懈，但一群人在一起就很有力量哈
