### ISSUE TITLE
第九次冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#53]

**Comment by sleepingshel** [comment]
今日进展：把按导师修改页面的接口对上了，修改了一些细节，然而还是没有学会<if>标签
存在问题：不会<if>标签，感觉现在的逻辑有点怪怪的，但是不知道要怎么从哪里下手改。。。。。。
明日安排：再理一遍整个院负责人的逻辑，修改一些细节
心得体会：哈哈，哈哈哈

**Comment by Wangtingting007** [comment]
今日进展：修复诸多BUG，完善细节
存在问题：还是存在一些bug
明日安排：继续修复bug,完善细节
心得体会：马上有时间逛街逛街逛街！！！！

**Comment by weeway** [comment]
今日进展：完成了所有界面
存在问题：对 DOM 操作不熟悉，还要继续看
明日安排：把界面跑一遍，看看有没有bug
心得体会：alpha 版本就要发布了啊！

**Comment by xuowner** [comment]
今日进展：脱线中
存在问题：无
明日安排：运行一下alpha版本的页面，哈哈哈哈
心得体会：我要好好睡觉

**Comment by SANDWICHLiam** [comment]
今日进展：继续研究算法，还没有成功把cpp文件从php调用成功，修改了下匹配设置界面的可选导师和确认分配按钮，系负责人已经可以手动给学生分配导师，数据库字段修改：把tc_issue表中的totalNow字段删除，新增nowExper/目前实验班学生数和nowNatur/目前自然班学生数字段
存在问题：匹配设置界面的智能分配alpha版本可能还无法上线。。我要离线了。。
明日安排：整合下代码，数据库数据添加，完整的运行下alpha版本的导师智能分配系统
心得体会：alpha版本这么快就要发布了，感觉在这三周的冲刺开发，队友都太牛逼啦，组长也很辛苦，估计身体都快被掏空了，算法啊！！还一直在处理要如何导入，脑袋都大了。。总之，大家都在不断的努力完善项目，加油吧！

**Comment by yootao** [comment]
今日进展：大概理了一下院负责人的功能流程，然后学习了一下伟炜写的代码
存在问题：啊啊啊，js还不熟悉
明日安排：看看哪里还有bug，最后再完善一下
心得体会：在各位大佬队友的努力下，alpha终于要出啦，期待ing...
