### ISSUE TITLE
第十次冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#54]

**Comment by SANDWICHLiam** [comment]
今日进展：我改了一天的代码了！！很烦躁！！！
存在问题：我改了一天的算法了！！！！快弄好了！！！很烦躁！！！！
明日安排：明天发布Alpha版本！如果改需求我就去跳楼！！
心得体会：我改了一天的算法了！！我改了一天的算法了！！我改了一天的算法了！！烦躁的事情说三遍！！！

**Comment by xuowner** [comment]
今日进展：修改PM认为不够完善的地方
存在问题：看着楼上烦躁，表示很心安！
明日安排：做编译，做编译，做编译
心得体会：果然还是看别人改bug的心情好，蹭蹭蹭！

**Comment by sleepingshel** [comment]
今日进展：改了几个细节
存在问题：无所畏惧.jpg
明日安排：回家玩耍，次好次的
心得体会：整合代码好坑啊，代码莫名变了，不出BUG还感觉不出来

**Comment by Wangtingting007** [comment]
今日进展：修改BUG
存在问题：没有问题
明日安排：复习人工
心得体会：终于轻松了

**Comment by weeway** [comment]
今日进展：系负责人时间设计界面 添加 起止时间是否合法的判断，重构了 js 代码
存在问题：添加功能时，出现了一个出现了一个bug。把代码看了好几次，才发现是复制之前的代码时，忘记改变量名了！！！摊手~
明日安排：好好学习！
心得体会：明天就要发布 alpha 版本！~鸡冻~

**Comment by yootao** [comment]
今日进展：根据齐民提的需求，对算法进行近一步的修改
存在问题：改起来还是很顺利的，没什么问题
明日安排：明天围观alpha的发布！
心得体会：果然算法还是老本行，改起来轻松无鸭梨。
