### ISSUE TITLE
学长经验交流会——心得体会

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#59]

**Comment by Wangtingting007** [comment]
昨天听学长讲了许多许多许多，感触很深很深很深，感觉软工实践这门课真的真的真的很棒很棒很棒。栋帅这种新型的教学模式真的很有意义很有意义很有意义，然后我们应该很认真很认真很认真对待它!😁😁😁

**Comment by sleepingshel** [comment]
感想：其实我一直在沉迷代码和BUG无法自拔，所以听学长分享经验是断断续续听的，难得学长来分享一次本来应该好好听的，可是代码要敲不完了。学长讲的面试经验感觉在其他地方也听过很多遍，也可能有一些独特的地方被我漏掉了吧，感想最深的还是学长分享的在软工上的收获。学长说他们GITHUB是不能随便PUSH的，要组长审核后才可以，这点有点吃惊，那组长得一行行代码看过去吗，他们组长好强啊。还有开会时间控制这一点，我们组也在控制开会时间，但那是因为开会时间晚，不想开太久，倒是没想到和以后工作相关。感觉对比起企业的开发流程来说，我们组还有很多地方很水，也在不断吸取经验，相信我们能超越学长他们。PS：我们也想要那本人月神话

**Comment by CStianya** [comment]
之前在学长学姐访谈的时候，我们采访的便是晓强学长的那一个小组，在访谈时，学长便已经将他们的很多心得体会分享给了我们，从项目把控、会议形式、时间安排、成员协作等等，不过那时分享的大都是关于Alpha版本的一些经验。这次课上的分享课，学长更多的是以自己实习的经历来告知我们软工的重要性。
从对安卓一无所知，到吃到了福州最好的自主餐厅，软工实践便是梦想的一个启航点。学长以软工为敲门砖，打开了许多公司的大门，便是对此最好的诠释。在学长的分享当中，我印象比较深的便是在公司里面，团队的运转方式有很多地方和软工实践都有相似之处，团队协同、站立式会议等等，软工实践可谓说便是一次微型的公司实习经历。只不过公司的站立式会议都有着严格的时间把控，会议时间也稍微比软工久一点，但我感觉有着时间的把控，这会更鞭策组员去总结自己的进展以及问题，去进行思考，更有利于项目的展开。站立式会议进行到现在也已经有八天了，每天一会确实让我对项目有了一个更清楚的了解，但相对于公司的运行方式，我还有很多做的不足的地方，不过在之后的beta版本冲刺中，我会尽量汲取学长的经验，努力改正。
最后，谢谢学长当时为我们辛辛苦苦整理的那么多文档代码，耐心得给我们解答问题，虽然之后因为一些原因没能接手你们的项目，但是你们让我们收获了许多，谢谢！

**Comment by xuowner** [comment]
论如何从一个小白到一个技术控的养成？自己和学长的相同点大概就是都是从小白开始，不同的是，我觉得我现在还是小白，应该多做努力，即使软工的作业都有参与，但是缺少的还是完成之后的总结吧，这一方面一直都不擅长，听了学长的分享，更相信的是总结是一定要有的，只有参与，完成，总结才能进步。还学到了很多的面试技巧，但能够使用这些技术的技巧的前提是要真真正正的做过才懂得，相信软工节课之后会有更深的感悟！

**Comment by SANDWICHLiam** [comment]
其实在听晓强学长分享他的软工历程前，我们团队已经找过晓强学长和他的组长进行了采访，采访的时候更多的是了解询问一些有关项目进展、技术方面等问题，但是这次课上晓强学长更多的分享的是自己在做软工过程中的心得体会，着实又安利了一波，也让我对日后的工作有了一些积极的想法，学长从对安卓一无所知到历时两个多月和团队做出报课安卓端，可见在软工上收获巨大，我自己也已经深有体会了，软工确实带给我很大的提升。不管是编码能力，还是对项目的理解把控；
从软功课开始到现在，感觉非常累，但是感觉收获也很大，不仅仅是在截止时间前熬夜，就算是平时，我也会不自觉的去熬夜敲代码，希望能够早点完成任务，听了晓强学长的分享后，对下一个beta版的冲刺阶段有了一定的期待，尽管alpha到现在还有一些问题存在，但是我们会尽力去解决，我们喜欢的是一起编码过程中一起学习知识，解决难题而建立的团队感情。

**Comment by weeway** [comment]
从开始软工实践的那一刻起，就开始了一次艰难但收获颇丰的磨砺。从学长的经历就可见一斑。在软工实践课上的收获，为他赢得了多家公司的 offer，足以说明软工实践可以带来的正向改变。小组项目从 android 转场 php ，我从做 android 变成做 web 前端。因为之前，大部分时间用的编码语言是 java，而且是做 android，对 php 和前端的技术不熟悉。开始的时候，很苦恼。但是经过，八天的冲刺和每天的站立式会议，慢慢地对前端熟悉起来。团队的分工和合作也明晰起来，团队磨合的越来越棒。听了学长的经验分享，我相信软工实践一定能够，给每个积极投入的回报以丰厚的收获。
