### ISSUE TITLE
改进《需求规格说明书》

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#6]
1. 对照国标，改进《需求规格说明书》并更新到git上
2. 说明增删的内容
3. 对老师所提问题进行分析

**Comment by yootao** [comment]
### 添加

- 版本历史
- 第二部分  需求分配 小节 
- 第三部分 外部接口需求 小节
- 第三部分 性能需求小节 需添加 压力特性要求（即对600人同时在线的处理方案)
- 第三部分 软件系统属性

### 删除

- 原2.3.2.3用户场景 part six 对两种分配算法的简介
- 原4.1.2功能描述（概要）
- 原4.5数据管理能力要求
- 原4.6其它专门要求
- 原第三部分 原型界面

### 调整

   => 代表调整到

- 原1.3 预期读者和阅读建议      => 	1.1 目的 部分
- 原第三部分 界面原型              =>          3.1.1 用户界面 小节
- 原4.4 输入输出要求                 =>          3.1.3 软件接口 和 3.1.4 通信接口 小节
- 原4.6 故障处理要求                 =>          3.6 软件系统属性 小节
- 原4.2.3 灵活性                         =>          3.6 软件系统属性 小节

**Comment by yootao** [comment]
#### 毕设导师分配系统_软件需求规格说明书（修改版）
- pdf：[点击查看][1]
- doc：[点击查看][2]

[1]:https://coding.net/s/6b45af4b-5406-445f-a702-30ad1790184e
[2]:https://coding.net/s/c5ee110b-e355-49c1-8529-bd59816436f2
