### ISSUE TITLE
Alpha版本心得体会

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#60]

**Comment by sleepingshel** [comment]
心得体会：哈哈哈哈哈哈，终于做完了alpha版本的功能，这十几天时间从开始学PHP基础到看ThinkPhp5框架，再到写出这几个功能，好久没有这么高的效率了，整个人愉快地要上天了。做之前一直觉得就两个页面，写得应该很快，还打算过完双十一花一天的时间做完，然后写第一个功能的时候就GG了，就一个简单的查询功能花了差不多三天的时间折腾，因为不熟悉PHP语法也部署写ThinkPhp5函数的用法，所以各种出错，先用链式查询，然后改成原生sql语句，后面发现想做分页还是要用链式，嗨呀好气啊。分页一直不会做，试着根据百度过来的方法来写，然后前端直接输出了我的代码，最后跟着齐民大大的代码写好了分页，但是各种出问题。还有就是导师修改的动态刷新，第一次写接口成功了，PHP写接口好方便啊，就是导师修改页面的赋值很麻烦，多重循环，整个人都不好了，熬夜熬到三点，终于做出来了，接口对接意外的简单。其实有一段时间，我一度以为自己要做不完了，结果竟然意外的做出来了。接下来只希望beta版本时间延迟一点，还有好多考试啊。最后：加需求就砍人，已准备好40米大刀。

**Comment by Wangtingting007** [comment]
哈哈哈哈哈哈哈，终于写完啦啦啦啦啦，可以逛街街街逛街街街!!!!
感觉自己收获还是蛮大的，第一当然是学会了新框架TP5啦，感觉TP5的分页好难用啊，老是有很多莫名其妙的BUG，直到现在还是不大了解这个分页是怎么个写法，基本上出了BUG就直接找齐名了（还好有大腿）。第二大感想就是感觉团队每个人都很棒啊，大家都能较好的完成自己的任务！！差不多就这样了
最后：加需求就砍人，已准备好40米大刀。

**Comment by xuowner** [comment]
听说就要发布Alapha版本了？三周的时间过的好快，对于一个电视迷来说，三周都要在敲代码中度过，是多么的蓝瘦。十天冲刺给我的最大体会就是：团队编程真的很不一样，比一个人在宿舍敲代码多了更多的干劲，遇到问题可以一起解决，有了当初结对编程的模样。队友的能力真的很强，学到了很多新技能。整个团队中，只有我的项目经历最少，感谢的是队友的不嫌弃，还给予了很大的支持，有人带着学习和PM的每天督促，完整的项目安排，才使得我这个没有自律力的每天至少都有敲一些代码，不至于像别的组那样，最后几天疯狂熬夜，通宵，还没有见到4点福大的太阳的我，该庆幸呢还是伤心呢？希望明天不要改需求啊，不然真要见到4点的福大了，熬夜真的伤身啊！！！

**Comment by SANDWICHLiam** [comment]
三周的冲刺时间过得好快，备战校运会和征战校运会花了好多的时间，每天训练得很累还是要敲一些代码，期间出了各种意想不到的bug，其实一开始我还是很怕即使使用了github，代码整合也会存在问题，实际上确实存在了一些小问题，三周的编程，我对PHP有了更深的了解，对前端有了一些了解（后台程序猿也确实需要了解一些前端），但是最大的收获是知道如何使用PHP调用c/c++算法，处理输入输出结果，感觉对性能的提升还是很有帮助的，很喜欢大家一起敲代码的氛围。

**Comment by weeway** [comment]
Alpha 版本发布前夜。现在时刻凌晨 1:31，坐标 33# 5楼活动室。软工实践课，从开始敲代码开始到现在十天的冲刺结束。在这十天里，除了赶软工实践课的项目，还要面对来自各科的压力。有各种的作业、实验，还有步步紧逼的四门考试。两次敲代码到深夜，身体也被掏空了两次！！！最终，完成了Alpha版本。这个过程中，看到了小组项目从0到1的变化和体会到队友们强大稳定的代码输出能力。自己也从不懂前端的菜鸟，变成了可以面向搜索引擎写出界面的菜鸟。大家一起团结协作的感觉超级棒！

**Comment by yootao** [comment]
什么？三周就这样过去了？？Alpha 版本就要发布了？？？本来想着写了这么久的文档，终于可以开始敲代码了，想想就有点激动。然而事实上并不是这样的，我对前端的知识是一无所知。在这十几天里，慢慢接触了html、css、js等知识，还有前端的测试工具Qunit等，算是稍微入了个门，能够写点东西出来了。但在冲刺期间，我还出了趟远门去参加acm的比赛，这使我的进度变得更加缓慢。不过还好有各位大腿队友的帮助，alpha版本还是如期的发布了！在发布前期，队友需要用php调用cpp写的分配算法，修改算法应该算是比较擅长的，按照队友的需求很快就能改好，期待算法最终能够整合到alpha版本中，拭目以待！

**Comment by CStianya** [comment]
从11月5日到11月19日凌晨三点，两个多星期来的Alpha版本冲刺，才真真正正深刻体会到软工实践何为魔鬼式课程。十分紧凑严格的任务安排以及详尽的作业要求，无论你是小白还是大神，无论你是否有过项目经历，竟然选择了软工实践，便得强迫自己去学习，去努力，即使通宵熬夜也得把项目完成出来。在Alpha版本作业发布之后，相信所有人的想法都是怎么可能完成？！！但是通过十天的冲刺博客了解，很显然许多组都坚持了下来，做得或好或差，坚持已然成为了一种习惯。团队一起敲代码、讨论某个BUG、为某个功能模块进行争辩、项目计划的安排等等等等，这十几天下来，虽说真的很累很累很很累，但是直到如今的凌晨三点多，看着项目我完美得运行着，那种喜悦的心情不言而喻，困乏的身体都瞬间精神了起来。
这一个多月来的软工实践，从最初的选题到如今的Alpha版本的发布，作为全职项目管理的我，磕磕碰碰在所难免。经常为了某个功能的实现效果和组员进行争辩，不过对于一个团队而言，意见的冲突才是前进的最强动力！思想的交流让我们的项目更加完善，也对自行存在的不足不停得进行反思以及改正。人生第一次以一个项目管理者的身份参与软工项目的经历确实感受很不一样，很多人都说PM不用敲代码，随便写几遍博客就好了多轻松。其实只有当过PM的人才知道PM有多累，组员完成自己的任务便可以休息，然而PM要随时把控所有任务的进度，某一阶段的任务完成之后，便得开始着手下一阶段的任务安排，从头到尾都无法休息。不过，虽然累真的很累，但幸好我有着一群非常靠谱、非常厉害的队友们！对于我给定的任务，他们都很好的完成的任务，有时完成的进度真的超乎我的想想。Alpha版本的成功发布，永远离不开组员们日日夜夜的付出！
十几天的时间，确实在大学学习里刻苦铭心的一段记忆，感觉我说的都队，感谢软工！Beta版本，我们一直都在！
