### ISSUE TITLE
四个个人信息界面

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#62]
增加四个用户的头像信息

**Comment by SANDWICHLiam** [comment]
新增学生的头像信息，可实现上传，并且保存修改前预览头像，后台已经实现
![default](https://cloud.githubusercontent.com/assets/15605479/20924081/97c7418a-bbea-11e6-8f66-1860de4605a9.png)

![default](https://cloud.githubusercontent.com/assets/15605479/20924099/b47391b2-bbea-11e6-8af8-f573faf0b0ea.png)

**Comment by SANDWICHLiam** [comment]
导师头像已增加

**Comment by SANDWICHLiam** [comment]
![default](https://cloud.githubusercontent.com/assets/15605479/20964825/13406a4e-bcae-11e6-90b4-d7a238e40084.png)

**Comment by SANDWICHLiam** [comment]
系负责人头像已加，后台已实现
![default](https://cloud.githubusercontent.com/assets/15605479/20976632/0f60ef5e-bcde-11e6-9e09-1d12b97cbcc4.png)

**Comment by SANDWICHLiam** [comment]
今日进展：1、改了学生的个人信息修改界面，加了旧密码验证，后台已更新实现
                  2、改了导师和系负责人的个人信息界面，修改了“修改”按钮的位置，在右上角新增头像显示
                  3、新增了导师个人信息修改界面和系负责人个人信息修改界面，后台已实现
存在问题：1、第一次上传头像不能预览，后面上传头像就可以预览了，不知道为什么，还没找到原因
                  2、JS实现旧密码的验证，一直失败，琢磨了一个多小时成功了
明日安排：1、把院负责人的个人信息界面和个人信息修改界面写完
                  2、数据库改进，有些表的命名需要修改，有些表需要新增字段，需要新增年级字段，需要重新  生成E-R图，重新生成各个表的信息和联系
心得体会：花了7个小时把学生的个人信息界面全部修改完成，然后剩下的三个用户组的个人信息修改界面就只需要复制黏贴就好了，JS真是好用，打算好好学习下前端知识，不懂得前端知识的后台程序猿不是一只好程序猿，好了我要睡觉了

**Comment by SANDWICHLiam** [comment]
院负责人头像已加，后台已实现
![default](https://cloud.githubusercontent.com/assets/15605479/20998661/647e6324-bd4a-11e6-93e7-b5b0c6aa83b3.png)

**Comment by SANDWICHLiam** [comment]
该模块完成
