### ISSUE TITLE
四个个人信息修改界面

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#63]
可对头像等信息进行修改

**Comment by SANDWICHLiam** [comment]
学生个人信息已经可以修改，并且可以上传头像，保存修改前实现头像预览，后台已实现
![default](https://cloud.githubusercontent.com/assets/15605479/20924118/c8f66d62-bbea-11e6-8dcb-ebaf61d784a1.png)

**Comment by SANDWICHLiam** [comment]
导师个人信息可以修改，并可上传头像，后台已实现
![default](https://cloud.githubusercontent.com/assets/15605479/20964868/3c64587c-bcae-11e6-8a20-4d1b7e02996d.png)

**Comment by SANDWICHLiam** [comment]
新增旧密码匹配功能，旧密码输入错误时，提示用户旧密码输入错误，学生个人信息修改界面同样实现
![default](https://cloud.githubusercontent.com/assets/15605479/20964891/57bed9e4-bcae-11e6-8ff2-ddfe1213bdf2.png)

**Comment by SANDWICHLiam** [comment]
系负责人个人信息可以修改，并可上传头像，后台已实现，所有修改个人信息的功能与学生、导师相同
![default](https://cloud.githubusercontent.com/assets/15605479/20976693/464691a4-bcde-11e6-92fb-ac7bf5c014cf.png)

**Comment by SANDWICHLiam** [comment]
**【细节修改】**

1. 新增新密码与旧密码不能相同的验证
2. 去除弹出框提示，新增新密码与确认密码判断是否相同，若不同，在确认密码旁提示
3. 页面更加人性化，去除了所有的弹出框提醒，改用JS判断后提醒

**Comment by SANDWICHLiam** [comment]
院负责人个人信息可以修改，并可上传头像，后台已实现，所有修改个人信息的功能与学生、导师、系负责人相同

**Comment by SANDWICHLiam** [comment]
该模块完成

**Comment by SANDWICHLiam** [comment]
**【细节修改】**

1. 旧密码输入错误，会自动聚焦在旧密码输入框，并提醒，正确则提醒消失
2. 新密码与旧密码相同时，会自动聚焦在新密码输入框，并提醒，不同时提醒消失
3. 确认密码与新密码不同时，会自动聚焦在确认密码输入框，并提醒，相同时提醒消失
