### ISSUE TITLE
登陆界面——错误提示

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#64]
- 沿用学长的提示模版
- 未输入用户名时提示“请先输入账户名”
- 未输入密码时提示“请先输入密码”

**Comment by SANDWICHLiam** [comment]
1. 帐号密码输入正确时，学生直接进入报课系统，导师、系负责人、院负责人进入教学选择界面，选择进入报课系统或者导师分配系统
2. 帐号密码输入错误时，从上滑下登录失败的提示
![default](https://cloud.githubusercontent.com/assets/15605479/21095986/d87f7852-c098-11e6-9197-b7ffd9b9c026.gif)
