### ISSUE TITLE
数据库——设计改进

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#65]
- 针对新增的年级需求，对数据库的表以及联系进行改进
- 生成改进后的数据库ER图以及各个表的信息

**Comment by SANDWICHLiam** [comment]
针对新的需求变动，和安卓组经过一个晚上的讨论，确定了（应该可能是最终版的）数据库，改进之后的数据表如下：
【学生表】（每年新建一张表）
![default](https://cloud.githubusercontent.com/assets/15605479/21017552/bd5db62a-bda4-11e6-81ca-e5ab0f706cb1.png)

【导师表】
![default](https://cloud.githubusercontent.com/assets/15605479/21017564/c4f67ade-bda4-11e6-8c5a-a411e8c33c2a.png)

【系负责人表】
![default](https://cloud.githubusercontent.com/assets/15605479/21017570/c8ab3c0a-bda4-11e6-8269-a4cd451d660e.png)

【院负责人表】
![default](https://cloud.githubusercontent.com/assets/15605479/21017573/cd75f360-bda4-11e6-8275-75c17fdcbfac.png)

【志愿表】（每年新建一张表）
![default](https://cloud.githubusercontent.com/assets/15605479/21017581/d0c7d8d0-bda4-11e6-895f-739306841ca2.png)

【志愿信息设置表】
![default](https://cloud.githubusercontent.com/assets/15605479/21017587/d4bdf6ae-bda4-11e6-8a01-0c883288cff7.png)

【课题信息表】（每年新建一张表）
![default](https://cloud.githubusercontent.com/assets/15605479/21017592/d8a0de08-bda4-11e6-91be-8559d5e03282.png)

【结果表】（每年新建一张表）
![default](https://cloud.githubusercontent.com/assets/15605479/21017606/dbfbdb5c-bda4-11e6-880f-4216d8259f2e.png)

【年级表】
![default](https://cloud.githubusercontent.com/assets/15605479/21017611/df2f5b8c-bda4-11e6-9bd9-273cf7d08c48.png)

【系负责人权限表】
![default](https://cloud.githubusercontent.com/assets/15605479/21017615/e2de691c-bda4-11e6-99f5-5addf4cadce3.png)

**Comment by SANDWICHLiam** [comment]
使用powerDesigner进行数据库更新设计
![powerdesigner](https://cloud.githubusercontent.com/assets/15605479/21018394/a9b48aa6-bda7-11e6-908d-f57a177960ab.png)
