### ISSUE TITLE
界面提示——规范化

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#67]
- 所有页面均有提示：当前所进行的是那一级的导师分配
- 提示格式默认为：提示1：。。。提示2：。。。
- 重要信息采用红色标识，例如时间段以及学生人数上限下限等。

**Comment by Wangtingting007** [comment]
所有页面均有提示：当前所进行的是那一级的导师分配
提示格式默认为：提示1：。。。提示2：。。。
重要信息采用红色标识，例如时间段以及学生人数上限下限等。

全部完成
