### ISSUE TITLE
毕设导师分配系统——Logo设计

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#68]

**Comment by yootao** [comment]
<del> 感觉审美已死... </del>
## logo1

![qq 20161214161131](https://cloud.githubusercontent.com/assets/16634624/21184362/29a967ba-c247-11e6-9747-e8e8a33cfaaf.png)

## logo2

![qq 20161214215651](https://cloud.githubusercontent.com/assets/16634624/21184630/42169d6c-c248-11e6-9886-649f1b2b3e5a.png)

**Comment by CStianya** [comment]
- 采用Logo1

**Comment by CStianya** [comment]
- 把Logo更新到登陆界面
- 进入每个系统后显示对应的Logo吧？把导师互选系统导航栏上的Logo也更新下
