### ISSUE TITLE
系负责人——学生管理界面

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#72]
- 同一级的学生不允许导入两个学号一致的学生
- 支持Excel的信息导入

**Comment by SANDWICHLiam** [comment]
学生列表接口已写好，API文档说明：http://www.showdoc.cc/10507?page_id=83431

**Comment by SANDWICHLiam** [comment]
1. 添加学生接口完成
2. 删除学生接口完成
3. API接口文档已更新：http://www.showdoc.cc/10507?page_id=83431

**Comment by SANDWICHLiam** [comment]
学生搜索接口已完成，所以接口说明文档已更新：http://www.showdoc.cc/home/item/show/item_id/10507

**Comment by CStianya** [comment]
- 返回信息按照学号顺序显示
- 导入信息时覆盖原有记录

**Comment by CStianya** [comment]
- 覆盖功能尚未实现
![0z1nn7c pvxyre _jd he](https://cloud.githubusercontent.com/assets/20432947/21220958/72404994-c2f6-11e6-9964-5a0dc1ece08f.png)

**Comment by SANDWICHLiam** [comment]
- 返回信息已修改为按照学号顺序显示
- 导入信息时覆盖原有记录，若为新纪录则添加

**Comment by CStianya** [comment]
- 单个新增导师时，对于错误的输入，提交后没有给出提示，用户体验不好
- 输入完成后，点击提交更改也没反应，数据库也没有新的记录添加
- 导入文件时，若存在相同的学号，则对应的记录会被删除（也可能是我本地的问题，明天再看看）
