### ISSUE TITLE
系负责人——学生管理界面

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#73]
- 同一级的学生不允许导入两个学号一致的学生，不同级的学生允许出现学号一致的学生
- 支持Excel的信息导入

**Comment by weeway** [comment]
**访问 [系负责人-学生管理界面](http://www.303studio.cn/public/index.php) 查看效果**
账号：031402209
密码：031402209

**Comment by weeway** [comment]
![](https://github.com/weeway/Netdisk/raw/master/pictures/student_manager1.gif)

**Comment by CStianya** [comment]
Test

**Comment by CStianya** [comment]
- 搜索接口的对接
- GIT图片演示

**Comment by weeway** [comment]
![](https://github.com/weeway/Netdisk/raw/master/pictures/%E5%AD%A6%E7%94%9F%E7%AE%A1%E7%90%86.gif)
