### ISSUE TITLE
用powerdesigner进行数据库设计，提供ER图

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#8]

**Comment by SANDWICHLiam** [comment]
E-R图
[毕设导师智能分配系统E-R图.pdf](https://github.com/Tutordistribution/Tutor-distribution/files/555127/E-R.pdf)

**Comment by SANDWICHLiam** [comment]
![e-r](https://cloud.githubusercontent.com/assets/15605479/19807681/d48f0ce8-9d53-11e6-9acf-e372d0f422b9.png)

**Comment by SANDWICHLiam** [comment]
powerdesigner数据库设计图
![powerdesigner](https://cloud.githubusercontent.com/assets/15605479/19808294/cb8b480c-9d56-11e6-8399-e5f702f7b47c.png)
