### ISSUE TITLE
系负责人——导师分配情况界面

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#93]
- 有年级的下拉框
- 功能模块信息和院负责人的导师分配情况基本一致
- 直接参照院负责人的结果界面复制黏贴进行开发
- 支持以Excel格式导出结果信息

**Comment by yootao** [comment]
![](http://images2015.cnblogs.com/blog/1018687/201612/1018687-20161212194713120-2131451069.png)

**Comment by CStianya** [comment]
导入导师数据后，界面显示正常点，分隔线要铺满

**Comment by yootao** [comment]
![](http://images2015.cnblogs.com/blog/1018687/201612/1018687-20161214154608667-1791607189.png)
