### ISSUE TITLE
系负责人——学生分配情况界面

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#94]
- 有系别和年级的下拉框
- 功能模块信息和院负责人的学生分配情况基本一致
- 直接参照院负责人的结果界面复制黏贴进行开发
- 支持以Excel格式导出结果信息

**Comment by sleepingshel** [comment]
做完了

**Comment by CStianya** [comment]
- 结果信息按照学生的学号信息排序显示
