### ISSUE TITLE
系负责人——学生分配情况界面

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#95]
- 有年级的下拉框
- 功能模块信息和院负责人的学生分配情况基本一致
- 直接参照院负责人的结果界面复制黏贴进行开发
- 支持以Excel格式导出结果信息

**Comment by yootao** [comment]
![](http://images2015.cnblogs.com/blog/1018687/201612/1018687-20161212180353839-1427552372.png)
