### ISSUE TITLE
第一次冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#96]

**Comment by SANDWICHLiam** [comment]
【今日进展】：1、改了学生的个人信息修改界面，加了旧密码验证，后台已更新实现
                  2、改了导师和系负责人的个人信息界面，修改了“修改”按钮的位置，在右上角新增头像显示
                  3、新增了导师个人信息修改界面和系负责人个人信息修改界面，后台已实现
【存在问题】：1、第一次上传头像不能预览，后面上传头像就可以预览了，不知道为什么，还没找到原因
                  2、JS实现旧密码的验证，一直失败，琢磨了一个多小时成功了
【明日安排】：1、把院负责人的个人信息界面和个人信息修改界面写完
                  2、数据库改进，有些表的命名需要修改，有些表需要新增字段，需要新增年级字段，需要重新  生成E-R图，重新生成各个表的信息和联系
【心得体会】：花了7个小时把学生的个人信息界面全部修改完成，然后剩下的三个用户组的个人信息修改界面就只需要复制黏贴就好了，JS真是好用，打算好好学习下前端知识，不懂得前端知识的后台程序猿不是一只好程序猿，好了我要睡觉了

**Comment by sleepingshel** [comment]
【今日进展】
确认了自己需要做的功能（就是还没开始做
【存在问题】
因为有两个人都有负责系负责人的修改，所以比较担心冲突。还有就是数据库要变了，感觉有好多东西要改的样子
【明日安排】
把院负责人的学生查询和导师查询两个功能里面要修改的内容先改掉
【心得体会】
又要开始肝代码了，朴实的微笑中透露着些许疲惫.jpg

**Comment by weeway** [comment]
**【今日进展】**

1. 时间设置界面更名为匹配设置界面
2. 初步完成学生管理界面，完成了基本的布局、弹窗以及样式美化
3. 匹配设置界面修复人数可为负的bug
4. 匹配设置界面增加第一、二轮时间合法性判断

**【存在问题】**

1. 学生管理界面需要上传 Excel 文件，但是还没有接触过文件上传。需要花时间去熟悉。 
2. 多个界面中的 close 按钮，存在的 bug 还没修复

**【明日安排】**

1. 了解文件上传的流程以及使用的技术和方法
2. 学生管理界面预留 ajax 局部刷新接口，准备和后台对接

**【心得体会】**

> 冲刺第一天就刚到了12点，又把 alpha 版本敲代码的那股劲给找回来了。因为之前重构了匹配设置界面的 js 代码。增加了代码的可读性，降低了代码间的耦合性。在 PM 增加需求的时候，只要在原来的基础上，做一些小修改。而不会牵一发而动全身。所以改起来很轻松。一个nice的开端！！！

**Comment by Wangtingting007** [comment]
【今日进展】

1.改了学生的可选导师、志愿填报、志愿结果界面中的提示，按照要求所给的规范（提示1：XXXX 。。。。以及对关键信息进行标红处理）将原有的提示进行修改，更加规范。
2.完善了志愿数可设置的功能，之前太过粗心一直以为志愿数就是5不可修改，就写死了，后面发现志愿数原来是可修改的，就在此完善了。
3.按照栋帅的要求将学生的志愿填报界面的下拉框进行修改，原本为其中某位导师，现在更改为  ===请选择=== 。
4.按照栋帅的要求将学生的最终结果界面进行修改，原本的选择同一的学生中没有该学生自己，现已按照要求加入该生自己。

【存在问题】

1.今日完成的任务是主要是对之前的小缺点进行修改，基本上没什么问题，之前的提示信息部分代码写的太过冗杂，所以之前这一部分的代码全部注释，重新在写，花了点时间。
2.自从改了需求以后发现自己需要修改的地方真的是超级超级超级多，（齐民说我还不如重写更快相比于修改。。。）我能怎么办.jpg     我也很绝望.jpg  。
3.除了需求变更所需要修改的地方以外，我发现由于之前的 志愿信息时间设置表有些问题，（当然我也错误的理解了这个表，一直以为第一轮填报志愿这个时间就包括学生填报志愿和导师选择学生。。。）然后我也不知道我要改多少。。。；另外还有 志愿表，之前为了自己方便，所以每次导师拒绝某个学生时，我是直接将该数据删掉的，这么做会导致后期的 智能分配就没办法做了，不过这个问题，在今晚和齐民讨论完之后，对志愿表新增某些字段后就解决了，但是问题就在于我这部分的代码也得改了。我好烦躁.jpg
4.由于新增了一个导师类型（既可以是计算机实验班导师，也可以是数学实验板导师，还可以是自然班导师），导师的课题填报页面需要修改，课题表也需要修改。 我好烦躁.jpg
5.由于新增了一个导师类型（既可以是计算机实验班导师，也可以是数学实验板导师，还可以是自然班导师），导师的可选学生页面需要修改，之前根据当前导师的类型会出现一个选择框（选项：自然班、实验班），主要是对导师的所有学生进行分类，分为自然班和实验班（实验班根据导师类型的不同，后台进行判断，即可显示出计算机实验班和数学实验班，因为之前一个导师顶多只可能是这两个实验班之一，所以计实和数实可以直接统称为实验班）进行查看。但是现在新增了那个鬼角色，前台部分的下拉框需要根据当前导师类型分为：无（0号角色导师） ， {自然班、计算机实验班}（1号角色导师） ， {自然班、数学实验班}（2号角色导师）， {自然班、计算机实验班、数学实验班}（3号角色导师）；然后不同的选择再跳不同.... 我好烦躁.jpg
6.最最最最最最最最最最最最烦躁的就是加了个年级字段了，起先听到这个消息的时候，还觉得说，啊，就该这个啊，这么一点点，很快啦啦啦。果然我还是太年轻，加入年级字段后，导师的最终结果页面就变得好复杂啊啊啊啊啊，起先是前端先加个下拉框，但是下拉框内的值哪里来呢，又不可能写死，思前想后，我觉得需要加个  年级表（就是一张里面只有一个字段：年级 的表）。。。虽然有点无语啦，但是还是要加的，再和安卓组、齐民进行了1小时的热烈讨论之后（当然不止讨论这个问题啦），我们终于解决了这个问题。。虽然解决了，但是感觉自己要奔溃了，怎么会有这么多要改的地方。。。。。。真的是应了那句，栋哥改需求，一跳解千愁！！！
7.导师的问题终于写完了，学生相比导师问题会少一点，学生下面的可选导师列表：1）新增导师搜索框，2）导师必须为仍有学生剩余数的（之前没有考虑到），但是由于又多了个导师角色类型，这部分就还要改。
8.恩，差不多问题就这些，算下来，之前写的6个界面都要改。。。。。。好想说脏话.jpg

【明日安排】

明天比较忙，可能能写代码的时间不多，但是貌似后天也好忙，我就还是先尽量完善下 学生的 
1.志愿填报（主要是导师的显示问题）、
2.可选导师（可以和志愿填报并行做，主要是对导师的显示问题进行修改，那个搜索再说吧，因为具体怎么搜索我还没理清）
3.志愿结果（好像貌似似乎没什么要改了），如果我还有时间的话 那我就顺便把 
4.导师详细信息做一下（比较简单的显示导师信息+选定导师为某志愿（这个可能大概应该是完不成，得等玲玲把界面写了））

【心得体会】
我真的好烦躁啊，这需求改的我也是醉醉的。。。。
不过很开心今天和安卓组一起讨论数据库，发现了不少问题，然后大家一起齐心协力解决这些问题，虽然花了漫长的时间，但是觉得很值得，自己对自己的项目更清晰，不仅局限于导师和学生这两个角色，还对系负责人、院负责人的相关功能更加了解，这样写的时候就会多多考虑自己所写的东西对其他功能的影响了。
讨论一番之后感觉这系统真是逆天啊，好复杂啊啊啊啊啊啊！！！！！
希望以后遇到的项目都可以在需求分析的时候就把问题都提出来，不希望这样半中央杀出一个该需求，还是这么致命的需求！！！！
mdzz,1：58了，睡觉。。。。

**Comment by yootao** [comment]
【今日进展】
了解beta版本中自己负责部分的需求变更内容

【存在问题】
需求变更后，alpha中写好的前端界面也要作相应的改变

【明日安排】
把 院负责人的结果查看界面 先写掉！

【心得体会】
自从改需求之后，数据库什么的要做相应的变动，这对后台的同学来说比较麻烦。而负责前端的我可能要改动的地方还不算多。但是在新增的需求任务里，对于后面系统的界面自适应，导师互选系统logo的设计这方面暂时还没有什么想法，看来还需要学习一波新知识...

**Comment by xuowner** [comment]
【今日进展】
对自己需要做的页面进行分析，然后做了一下beta冲刺的安排
【存在问题】
数据库变更之后，Alapha页面出现各种bug，需要在本地先写好自己的页面，等待后台修改后才能加进去
【明日安排】
写一下学生和导师的详细信息界面
【心得体会】
看了下beta冲刺的安排，心疼php的同学，要改的东西超级多，beta冲刺，我的任务比较轻，只能帮php的同学跑跑腿，买买夜宵了，哈哈哈哈哈
