### ISSUE TITLE
第二次冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#97]

**Comment by weeway** [comment]
**【今日进展】**

1. 匹配设置界面允许最少人数为0
2. 所有界面的左侧导航栏固定，不会随右侧页面滑动
3. 将一些全局的 css 样式添加到 backstage.css

**【存在问题】**

1. 这两天忙着做编译原理的语法分析器，花在 beta版本 上的时间比较少，之前的计划没有完全做完

**【明日安排】**

1. 完成学生管理界面的删除、新增学生的功能
2. 前端实现学生管理界面的分页

**【心得体会】**

> 这几天忙于做编译原理的实验，以至于没有把之前的安排做完。接下来这几天终于有时间，开始好好地敲软工的代码了~~~。

**Comment by SANDWICHLiam** [comment]
**【今日进展】**

1. 院负责人的个人信息界面和个人信息修改界面写完了
2. 数据库改进：user_student_2014表、tc_voluntary_2014表、tc_issues_2014表、tc_result_2014表的命名修改，目的是为了每年新建一张表便于区分；还有一些表修改了字段，新增或删除详情见数据库改进issue
3. 重新 生成E-R图，重新生成各个表的信息和联系，详情见数据库改进issue
4. 系负责人的所有页面，恢复了因数据库修改而造成无法正常显示的问题
5. 系负责人- 学生管理界面的学生列表及分页接口完成
6. 系负责人- 学生管理界面的新增学生接口完成
7. 系负责人- 学生管理界面的删除学生接口完成
8. 接口文档：http://www.showdoc.cc/10507?page_id=83431

**【存在问题】**

1. 路径问题出现的奇奇怪怪，感觉是TP的bug。。
2. 在智能分配方面，点击智能分配按钮，可能需要调用两次，实验班学生分配导师调用一次，自然班学生调用一次，但是在一个接口中实现，接口需要修改的地方可能比较多

**【明日安排】**

1. 需要完成智能分配算法接口的修改
2. 需要完成系负责人- 导师管理界面的导师列表及分页接口
3. 需要完成系负责人- 导师管理界面的新增导师接口
4. 需要完成系负责人- 导师管理界面的删除导师接口
5. 需要完成系负责人- 匹配结果界面的列表及分页接口

**【心得体会】**
因为新增了年级字段，之前写的前端和后台都需要修改，新增年级的选择，这个处理单个页面的工作量虽然不是很大，但是因为页面比较多，所以会花比较的时间；在alpha中采用视图的模版直接赋值，但是存在一些弊端，

**Comment by yootao** [comment]
【今日进展】
完成院负责人的结果查看界面，在导师和学生分配情况界面增加年级下拉框，以及支持excel导出。然后稍微修改了一下之前的布局。

【存在问题】
- 因为数据库有改动，一些后台的代码还没更新，从github上pull下来的最新版本并不能运行，所以只好先简单的修改让自己负责的部分能跑起来。
- excel导出的工作本来应该是后台要做的，结果我以为是前端的事情，然后就白做了...ORZ

【明日安排】
完成 系负责人的学生分配情况界面以及导师分配情况界面 

【心得体会】
每次敲前端代码，感觉自己真的是一无所知，对前端知识掌握的还太少，敲起来太不熟练了，经常得求助搜索引擎。然后有一些任务在做之前也要想清楚，不要到最后又得从新做或者是白做了，从而降低效率。

**Comment by xuowner** [comment]
【今日进展】
1.学生用户专业导师的详细信息页面
2.导师用户学生详细信息页面
【存在问题】
整体页面偏左，不够居中，修改css的时候没认真看好在哪个文件夹里，导致花了很多时间在改，却发现页面没有任何变化
【明日安排】
完成导师选择学生页面的弹出页面
【心得体会】
粗心害死人，我们的文件加上学长的文件，还是挺乱的，容易点错。体会到命名规范的重要性。

**Comment by Wangtingting007** [comment]
【今日进展】

根据更新的数据表，进行
1. 恢复alpha版本学生的可选导师页面原有功能
2. 恢复alpha版本学生的志愿填报页面原有功能
3. 恢复alpha版本学生的最终结果页面原有功能
4. 恢复alpha版本导师的填报课题页面原有功能
5. 恢复alpha版本导师的可选学生页面原有功能
6. 恢复alpha版本导师的最终结果页面原有功能

【存在问题】

1. 数据库变化太大，每个页面都要改。。。（仅仅只是恢复下原有功能）
2. 进度貌似有点慢，大家beta版本基本都在做原本计划中的任务，我还在恢复alpha功能。。。

【明日安排】
完成beta版本新功能
1. 学生的可选导师页面：可选导师按照名字来排序，导师所带人数到达限制则不显示该导师
2. 学生的志愿填报页面：同上
3. 学生的查看可选导师的详细信息

【心得体会】

好烦躁，不想说话

**Comment by sleepingshel** [comment]
【今日进展】
根据数据库的修改，回复alpha版本的按照导师查看匹配结果、按照导师修改匹配结果、按照学生查看匹配结果、按照学生修改匹配结果
【存在问题】
各种蜜汁BUG，分页BUG，数据库字段按BUG，前端显示BUG，还要加各种参数，想想就累
【明日安排】
把院负责人的匹配结果界面和修改界面的年级字段加上去，还有导师加上系别的筛选
【心得体会】
每次合并完总会出一点问题，有的时候会出很多问题，有一段时间没碰这个项目了，现在看到代码都在想自己当初到底在写什么，alpha版本好多细节没完善，现在各种问题就出来了
