### ISSUE TITLE
第三次冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#98]

**Comment by SANDWICHLiam** [comment]
**【今日进展】**

1. 系负责人- 导师管理界面的导师列表及分页接口已经完成
2. 系负责人- 导师管理界面的新增导师接口已经完成
3. 系负责人- 导师管理界面的删除导师接口已经完成
4. 系负责人- 匹配结果界面的列表及分页接口已经完成
5. 修改了学生列表接口，将返回总学生数改成返回总页数
6. 登陆界面跳转，修改回之前学长做的登录跳转的效果
7. 智能分配接口修改完成，修改部分：计算机实验班与数学实验班单独处理，即实验班可提前进行导师智能分配，对算法参数的传入值进行了修改，对于实验班来说，传入计算机/数学实验班学生学号、志愿和可带计算机/数学实验班的导师的工号、可带学生数
8. 更新接口文档：http://www.showdoc.cc/10507?page_id=83431

**【存在问题】**

1. 看似一个很小的功能，为了能够做得完美，操作更加人性化，其实需要花很大的时间去实现和完善改进，所以会花去较多的时间
2. phpExcel导出还没有实现，还没看懂学长的代码

**【明日安排】**

1. 学习phpExcel，先实现Excel的过滤和导入数据库
2. 智能匹配后的会生成3个文件：经过算法得到分配的学生对应导师信息、经过算法仍然未得到分配的学生、经过算法分配后每个导师的学生信息，处理这些文件，转换为JSON数据格式，并封装成接口，实现分页

**【心得体会】**
因为在alpha版本主体功能已经基本实现好了，所以beta版本是对alpha版本的细节完善，对于有完美强迫症的患者来说，细节修改真是太痛苦了，一定要改到非常的人性化；这几天的冲刺，PM的任务分配能力又厉害了，反正我是没有熬夜了，也能完成每天的任务，而且能够提前完成一些接口，还能有些时间来进行课业学习，感谢PM

**Comment by Wangtingting007** [comment]
【今日进展】

1.学生的可选导师页面：可选导师按照名字来排序，导师所带人数到达限制则不显示该导师
2.学生的查看可选导师的详细信息（课题信息）。
3.完善学生的志愿填报页面的导师下拉框，详情同可选导师页面。
4.学生的志愿填报 新增志愿轮数（后台），志愿为空时的错误提醒 ，志愿数的设置。 
4.学生的最终页面 同导师学生加入自己。
5.导师的填报课题页面 增加计算机实验班、数学实验班
6.导师的最终结果页面 新增可选年级功能（后台部分，前台还没出就还没赋值）

【存在问题】

1.github使用不熟练导致写完的东西不知道怎么就被吃了。。。

【明日安排】

1.学生的可选导师的 导师查找功能（导师搜索功能）
2.导师的可选学生 学生信息 接口
3.其他的看下明天前端部分哪里完成，赋值以下就好了。

【心得体会】
因为在alpha版本的功能都需要进行修改，所以有点烦，还有个XX的事情就是昨晚熬夜写的alpha版本的功能恢复好像不知道被什么给吃了（给他湖北 用的不够熟练）。
边听歌边写代码真的是很享受的事情啊！

**Comment by sleepingshel** [comment]
【今日进展】
系负责人- 学生结果显示
系负责人-导师结果显示
院负责人-导师结果修改的接口的修改
【存在问题】
因为加了年级所以数据表要各种改
分配系负责人功能的逻辑不是很清晰
【明日安排】
实现院负责人的系负责人显示和修改功能
【心得体会】
beta版本的进展意外顺利，一方面是对语言和框架更加熟悉，另一方面是PM安排的比较合理。每次一起开会敲代码进度总是惊人的，感觉所剩任务不多了，这次的冲刺比起alpha轻松很多，也少了很多紧迫感，争取早日写完功能然后慢慢改细节，希望在这次的展示会比上次顺利

**Comment by xuowner** [comment]
【今日进展】
1.普通导师-选择/拒绝学生弹出框
2.院负责人-管理系负责人
【存在问题】
很多小细节上面的问题都没有改进，页面太粗糙，git使用不熟练，遇到冲突不会解决，前端要用js的内容不会实现
【明日安排】
1.普通导师-最终结果增加年级下拉框
2.普通导师-课题提交——多重角色的布局
3.学生用户-专业导师页面增加搜索功能
4.学习一下怎么用js实现页面刷新和数据的传送
【心得体会】
本来以为自己的页面都写好了，可以休息了，没想到很多小细节没有考虑到，多亏了跟我一起合作的php编码同学的提醒，感觉身体被掏空了，还有很多任务没有完成，相对于其他的同学，由于没有学过js，只能加班加点了。蓝瘦，香菇！

**Comment by yootao** [comment]
【今日进展】
- 完成系负责人的学生结果和导师结果的界面显示
- 跟后台数据接口的对接
- 修复若干问题

【存在问题】
因为对js还不是很熟悉，所以在跟后台对接接口的时候出现各种问题

【明日安排】
开始进行系统logo的设计，然后ps什么的不是很会...

【心得体会】
由于PM在alpha版本强大的安排组织能力，所以现在beta版本自己要修改、新增的地方不是很多。但是在跟后台对接的时候还是会存在各种各样的问题，希望自己也能从中不断汲取经验，提升编码能力和开发效率！

**Comment by weeway** [comment]
**【今日进展】**

1. 完成学生列表分页功能
2. 完成单个或多个学生的删除功能
3. 完成和后台年级数据的对接

**【存在问题】**

1. 接口对接上需要先沟通好，才能避免花费额外的时间
2. 熟练使用 chrome 的 console，会少踩坑 

**【明日安排】**

1. 完成学生管理界面新增学生的功能
2. 完成学生管理界面搜索功能

**【心得体会】**

> 在前端的页面中使用了 vue.js，加快了数据到视图绑定。虽然前后端分离，会加大工作量。但是也会使前端处理逻辑更加顺畅。明天继续加油！！！
