### ISSUE TITLE
第四次冲刺——组员总结

### ISSUE THREAD

**Issue by CStianya** [Tutordistribution/Tutor-distribution#99]

**Comment by xuowner** [comment]
【今日进展】
1.修改了院负责人管理系负责人的页面
2.修改了学生详细信息页面--选择/拒绝按钮增加弹出框
3.修改了老师列表页面--增加了搜索框
4.修改了一堆蜜汁细节
【存在问题】
1.做管理系负责人页面的时候，div没有闭合，花了很久的时间在改bug，还有就是浏览器的适配问题，列表迷之少了竖线和横线
2.昨天安排今天要学会js，结果没有开展，任务没有完成，导致不能喝后台的同学完成对接
【明日安排】
1.边学边完成管理系负责人的各种前端接口，完成对接
【心得体会】
div闭合问题简直会逼死人，在几百行的代码中不断的找，眼睛都要瞎了，十分烦躁。效率不够高，没有办法跟上队友的脚步，更烦。总结今天一天，就是烦，烦，烦；跟队友的角色互换了，前几天悠闲，今天就吃到了苦果。

**Comment by SANDWICHLiam** [comment]
**【今日进展】**

1. 根据前端的需求修改学生管理界面的接口
2. 修改导师管理界面的接口
3. 测试学长的excel上传接口
4. 完成excel上传接口，实现了将excel中的数据添加入数据库中
5. 更新接口文档：http://www.showdoc.cc/10507?page_id=83431

**【存在问题】**

1. github的使用问题还存在一些问题，有时候还会存在冲突，而这个冲突就像雪球一样不及时处理会越滚越大
2. 对算法接口的修改，对大量数据的修改，与数据库的大量交互可能会造成使用智能分配时，速度较慢，还不知道怎么修改接口

**【明日安排】**

1. excel的导入功能已经实现，剩下excel导出功能需要完成
2. 根据前端需求，修改智能分配界面的接口

**【心得体会】**
今天再一次感到编程的魅力，在遇到难题时，当还没有全力以赴去面对难题的时候，在心里会暗示自己这个难题需要很久时间，说不定还无法解决，但是其实只要静下心来，把难题一步步的拆解开，一步步的解决；比如算法调用，excel导入导出，其实都是很简单的问题，是自己把它们复杂化了。

**Comment by sleepingshel** [comment]
【今日进展】
完成院负责人分配系负责人页面的赋值
修改了一些BUG
完善了一些细节
【存在问题】
今天效率蜜汁低下，显示从git上pull以后代码莫名少了一些，然后就是以前没做清楚的一些功能修修改改花了半天。
【明日安排】
写接口，然后和许总写的页面进行对接
【心得体会】
果然修改代码是比新写一个功能累多了。之前做系负责人的两个页面的时候直接把之前写好的黏贴过去，很多细节没有注意，导致折腾了很久。以后写代码要做好备注，以免时间一长又忘了。

**Comment by Wangtingting007** [comment]
【今日进展】
1.提示信息更加人性化
2.导师的可选学生 查看具体信息（后台+赋值）
3.导师的最终结果 按年级查询（后台部分，前台有个不知道是什么的鬼BUG）
4.导师的可选学生 具体信息页面中选择和拒绝功能（由于数据表字段的变化重新写了，今天发现新BUG就修改了下）
5.学生的专业导师方面的 导师具体信息页面实现根据学生身份的不同来进行显示不同的课题人数限制（自然班、计算机实验班、数学实验班）
6.学生的专业导师列表的BUG（之前写错了导致部分导师无法查询到，现已修复改bug）
【存在问题】
1.导师的最终页面 的年纪下拉框无法加入<a>标签导致页面暂时还没办法跳转，队友太忙了，办法已经找到了，明天尽量实现下。
2.导师的填报课题的bug真的是醉醉的。。。
3.虽然也写了一下午，但是原本今天的任务似乎都没怎么完成，修复一下午的边边角角。
【明日安排】
1.学生的可选导师的 导师查找功能（导师搜索功能）
2.修复填报课题的bug
3.修复导师的最终页面的 年级选择框问题
4.GIF搞起来！
【心得体会】
熬夜赶进度还是很有必要的，之前一直觉得自己快奔溃了，熬了两晚发现还是可以跟上大家进度的，跟上进度的感觉真是超级好啊，写代码心情都比较轻松。今天发现边边角角的东西真的是有够多啊，虽然今天也写了一下午，不过貌似都没有很高效，原本还想今天下午就把所有GIF都搞一下，东修修西补补一下午就过去了，希望明天能把GIF搞起来~~
有点担心队友啦，真么短的时间还要学习js,加油💪💪

**Comment by weeway** [comment]
**【今日进展】**

1. 对接学生管理界面搜索接口
2. 对接学生管理界面文件上传接口
3. 对接增加学生接口
4. 重构 js 代码

**【存在问题】**

1. 新增学生界面，没有花太多时间修改，看起来很粗糙
2. js 代码想到一个功能便加一段代码，没有良好的结构，导致后面回头修改时一头雾水

**【明日安排】**

1. 根据后台增加、删除、搜索接口完成导师管理界面
2. 对界面进行修改美化

**【心得体会】**
> 之前想自己手敲文件上传功能，然后再实现一下进度条。但是由于，bate版本开发时间紧迫。就想着偷懒一下，看看有没有现成的插件可以用。上“同性交友网站”搜索了一下，果然有很多插件都可以。灰常开心地挑了一个直接用！想偷懒就上github吧！
